#Makefile for actions si or isp driver and the sensors of actions support

obj-y				+= owl_host/
obj-y				+= owl_isp/
obj-y               += owl_imx/

obj-y				+= ov5645/
obj-y				+= imx0219/
obj-y				+= gc5004/
obj-y				+= gc2755/
obj-y				+= gs5604/
obj-y				+= ov2685/

obj-y				+= flashlight/

