#Makefile for actions si or isp driver and the sensors of actions support

#obj-$(CONFIG_ACTIONS_CAMERA) += owl_host/
obj-$(CONFIG_OWL_CAMERA_ISP) += owl_isp/
obj-$(CONFIG_OWL_CAMERA_ISP) += owl_imx/
obj-$(CONFIG_OWL_CAMERA_SI) += owl_si/
obj-$(CONFIG_GC5004) += gc5004/
obj-$(CONFIG_GC2755) += gc2755/
obj-$(CONFIG_GC2155) += gc2155/
obj-$(CONFIG_GC0312) += gc0312/
obj-$(CONFIG_GC2035) += gc2035/
obj-$(CONFIG_GS5604) += gs5604/
obj-$(CONFIG_IMX0219) += imx0219/
obj-$(CONFIG_OV2685) += ov2685/
obj-$(CONFIG_OV5645) += ov5645/
obj-$(CONFIG_TC358749) += tc358749/
obj-$(CONFIG_FLASHLIGHT) += flashlight/

