/*
 * Actions OWL SoCs ISP driver
 *
 * Copyright (c) 2015 Actions Semiconductor Co., ltd.
 * Shiheng Tan <tanshiheng@actions-semi.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License v2 as published by
 * the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef __BISP_REG_H__
#define __BISP_REG_H__

#define     MODULE_BASE                  0xE0270000
#define     MODULE_ENABLE                (MODULE_BASE+0x00)
#define     BUS_PRIORITY_CTL             (MODULE_BASE+0x04)
#define     RAW_RB_PRELINE_SET           (MODULE_BASE+0x10)
#define     CH_PRELINE_SET               (MODULE_BASE+0x14)
#define     CH1_ROW_RANGE                (MODULE_BASE+0x18)
#define     CH1_COL_RANGE                (MODULE_BASE+0x1C)
#define     CH2_ROW_RANGE                (MODULE_BASE+0x20)
#define     CH2_COL_RANGE                (MODULE_BASE+0x24)
#define     RAW_SKIP_SIZE                (MODULE_BASE+0x28)
#define     RAW_RB_SIZE                  (MODULE_BASE+0x30)
#define     RAW_RB_COL_RANGE             (MODULE_BASE+0x34)
#define     ISP_CTL                      (MODULE_BASE+0x40)
#define     VTD_CTL                      (MODULE_BASE+0x44)
#define     BV_DATA0                     (MODULE_BASE+0x48)
#define     BV_DATA1                     (MODULE_BASE+0x4C)
#define     BA_OFFSET0                   (MODULE_BASE+0x50)
#define     BA_OFFSET1                   (MODULE_BASE+0x54)
#define     TEST_PATTERN_CTL             (MODULE_BASE+0x58)
#define     ISP_LSC_REG_ADR              (MODULE_BASE+0x60)
#define     ISP_LSC_SETTING              (MODULE_BASE+0x64)
#define     ISP_DPC_THRESHOLD            (MODULE_BASE+0x70)
#define     ISP_DPC_NR_THRESHOLD         (MODULE_BASE+0x74)
#define     ISP_BPI_NR_THRESHOLD         (MODULE_BASE+0x78)
#define     ISP_CG_B_GAIN                (MODULE_BASE+0x80)
#define     ISP_CG_G_GAIN                (MODULE_BASE+0x84)
#define     ISP_CG_R_GAIN                (MODULE_BASE+0x88)
#define     ISP_SECOND_CG_B_GAIN         (MODULE_BASE+0x90)
#define     ISP_SECOND_CG_G_GAIN         (MODULE_BASE+0x94)
#define     ISP_SECOND_CG_R_GAIN         (MODULE_BASE+0x98)
#define     ISP_CC_CMA1                  (MODULE_BASE+0xa0)
#define     ISP_CC_CMA2                  (MODULE_BASE+0xa4)
#define     ISP_CC_CMA3                  (MODULE_BASE+0xa8)
#define     ISP_CC_CMA4                  (MODULE_BASE+0xac)
#define     ISP_CC_CMA5                  (MODULE_BASE+0xb0)
#define     RGB_GC_LUT_RST               (MODULE_BASE+0xc0)
#define     RGB_GC_COEFF                 (MODULE_BASE+0xc4)
#define     STAT_CTL                     (MODULE_BASE+0xd0)
#define     ISP_STAT_REGION_Y            (MODULE_BASE+0xd4)
#define     ISP_STAT_REGION_X            (MODULE_BASE+0xd8)
#define     ISP_WB_PRE_THROD_0_0         (MODULE_BASE+0x100)
#define     ISP_WB_PRE_THROD_0_1         (MODULE_BASE+0x104)
#define     ISP_WB_PRE_THROD_0_2         (MODULE_BASE+0x108)
#define     ISP_WB_PRE_THROD_0_3         (MODULE_BASE+0x10c)
#define     ISP_WB_PRE_THROD_1_0         (MODULE_BASE+0x110)
#define     ISP_WB_PRE_THROD_1_1         (MODULE_BASE+0x114)
#define     ISP_WB_PRE_THROD_1_2         (MODULE_BASE+0x118)
#define     ISP_WB_PRE_THROD_1_3         (MODULE_BASE+0x11c)
#define     ISP_WB_PRE_THROD_2_0         (MODULE_BASE+0x120)
#define     ISP_WB_PRE_THROD_2_1         (MODULE_BASE+0x124)
#define     ISP_WB_PRE_THROD_2_2         (MODULE_BASE+0x128)
#define     ISP_WB_PRE_THROD_2_3         (MODULE_BASE+0x12c)
#define     ISP_WB_PRE_THROD_3_0         (MODULE_BASE+0x130)
#define     ISP_WB_PRE_THROD_3_1         (MODULE_BASE+0x134)
#define     ISP_WB_PRE_THROD_3_2         (MODULE_BASE+0x138)
#define     ISP_WB_PRE_THROD_3_3         (MODULE_BASE+0x13c)
#define     ISP_WB_B_THROD_0_0           (MODULE_BASE+0x140)
#define     ISP_WB_B_THROD_0_1           (MODULE_BASE+0x144)
#define     ISP_WB_B_THROD_1_0           (MODULE_BASE+0x148)
#define     ISP_WB_B_THROD_1_1           (MODULE_BASE+0x14c)
#define     ISP_WB_B_THROD_2_0           (MODULE_BASE+0x150)
#define     ISP_WB_B_THROD_2_1           (MODULE_BASE+0x154)
#define     ISP_WB_B_THROD_3_0           (MODULE_BASE+0x158)
#define     ISP_WB_B_THROD_3_1           (MODULE_BASE+0x15c)
#define     ISP_STAT_CSC_Y_OFFSET        (MODULE_BASE+0x180)
#define     ISP_STAT_CSC_CB_OFFSET       (MODULE_BASE+0x184)
#define     ISP_STAT_CSC_CR_OFFSET       (MODULE_BASE+0x188)
#define     ISP_STAT_CSC_Y_R             (MODULE_BASE+0x18c)
#define     ISP_STAT_CSC_Y_G             (MODULE_BASE+0x190)
#define     ISP_STAT_CSC_Y_B             (MODULE_BASE+0x194)
#define     ISP_STAT_CSC_CB_R            (MODULE_BASE+0x1a0)
#define     ISP_STAT_CSC_CB_G            (MODULE_BASE+0x1a4)
#define     ISP_STAT_CSC_CB_B            (MODULE_BASE+0x1a8)
#define     ISP_STAT_CSC_CR_R            (MODULE_BASE+0x1ac)
#define     ISP_STAT_CSC_CR_G            (MODULE_BASE+0x1b0)
#define     ISP_STAT_CSC_CR_B            (MODULE_BASE+0x1b4)
#define     ISP_Y_REGION_Y               (MODULE_BASE+0x1c0)
#define     ISP_Y_REGION_X               (MODULE_BASE+0x1c4)
#define     ISP_COLOR_TEMPERATURE0_YR    (MODULE_BASE+0x1d0)
#define     ISP_COLOR_TEMPERATURE0_XSE   (MODULE_BASE+0x1d4)
#define     ISP_COLOR_TEMPERATURE0_YSE   (MODULE_BASE+0x1d8)
#define     ISP_COLOR_TEMPERATURE1_YR    (MODULE_BASE+0x1dc)
#define     ISP_COLOR_TEMPERATURE1_XSE   (MODULE_BASE+0x1e0)
#define     ISP_COLOR_TEMPERATURE1_YSE   (MODULE_BASE+0x1e4)
#define     ISP_COLOR_TEMPERATURE2_YR    (MODULE_BASE+0x1e8)
#define     ISP_COLOR_TEMPERATURE2_XSE   (MODULE_BASE+0x1ec)
#define     ISP_COLOR_TEMPERATURE2_YSE   (MODULE_BASE+0x1f0)
#define     ISP_COLOR_TEMPERATURE3_YR    (MODULE_BASE+0x1f4)
#define     ISP_COLOR_TEMPERATURE3_XSE   (MODULE_BASE+0x1f8)
#define     ISP_COLOR_TEMPERATURE3_YSE   (MODULE_BASE+0x1fc)
#define     ISP_COLOR_TEMPERATURE4_YR    (MODULE_BASE+0x200)
#define     ISP_COLOR_TEMPERATURE4_XSE   (MODULE_BASE+0x204)
#define     ISP_COLOR_TEMPERATURE4_YSE   (MODULE_BASE+0x208)
#define     ISP_COLOR_TEMPERATURE5_YR    (MODULE_BASE+0x20c)
#define     ISP_COLOR_TEMPERATURE5_XSE   (MODULE_BASE+0x210)
#define     ISP_COLOR_TEMPERATURE5_YSE   (MODULE_BASE+0x214)
#define     ISP_CSC_Y_OFFSET             (MODULE_BASE+0x2a0)
#define     ISP_CSC_CB_OFFSET            (MODULE_BASE+0x2a4)
#define     ISP_CSC_CR_OFFSET            (MODULE_BASE+0x2a8)
#define     ISP_CSC_Y_R                  (MODULE_BASE+0x2ac)
#define     ISP_CSC_Y_G                  (MODULE_BASE+0x2b0)
#define     ISP_CSC_Y_B                  (MODULE_BASE+0x2b4)
#define     ISP_CSC_CB_R                 (MODULE_BASE+0x2b8)
#define     ISP_CSC_CB_G                 (MODULE_BASE+0x2bc)
#define     ISP_CSC_CB_B                 (MODULE_BASE+0x2c0)
#define     ISP_CSC_CR_R                 (MODULE_BASE+0x2c4)
#define     ISP_CSC_CR_G                 (MODULE_BASE+0x2c8)
#define     ISP_CSC_CR_B                 (MODULE_BASE+0x2cc)
#define     ISP_CSC_CONTROL              (MODULE_BASE+0x2d0)
#define     BC_YGC_LUT_RST               (MODULE_BASE+0x300)
#define     BC_YGC_COEFF                 (MODULE_BASE+0x304)
#define     LY_LUT_RST                   (MODULE_BASE+0x308)
#define     LY_COEFF                     (MODULE_BASE+0x30c)
#define     DE_GAMMA_LUT_RST             (MODULE_BASE+0x310)
#define     DE_GAMMA_LUT                 (MODULE_BASE+0x314)
#define     FCS_LW_GAIN_RST              (MODULE_BASE+0x330)
#define     FCS_LW_GAIN_LUT              (MODULE_BASE+0x334)
#define     CCS_CTL                      (MODULE_BASE+0x338)
#define     ISP_CONTRAST_SETTING         (MODULE_BASE+0x350)
#define     ISP_SATURATION_SETTING       (MODULE_BASE+0x360)
#define     ISP_HUE_SETTING              (MODULE_BASE+0x370)
#define     ISP_BRIGHTNESS_SETTING       (MODULE_BASE+0x378)
#define     ISP_OUT_FMT                  (MODULE_BASE+0x3b0)
#define     ISP_OUT_ADDRY                (MODULE_BASE+0x3b4)
#define     ISP_OUT_ADDRU                (MODULE_BASE+0x3b8)
#define     ISP_OUT_ADDRV                (MODULE_BASE+0x3bc)
#define     ISP_STAT_ADDR                (MODULE_BASE+0x3c0)
#define     ISP_RAW_INPUT_ADDR           (MODULE_BASE+0x3e0)
#define     RAW_OUT_ADDR                 (MODULE_BASE+0x3f0)
#define     YUV_OUT_FMT                  (MODULE_BASE+0x400)
#define     YUV_OUT_ADDRY                (MODULE_BASE+0x404)
#define     YUV_OUT_ADDRU                (MODULE_BASE+0x408)
#define     YUV_OUT_ADDRV                (MODULE_BASE+0x40c)
#define     AF_CTRL                      (MODULE_BASE+0x420)
#define     AF_SPACE                     (MODULE_BASE+0x424)
#define     AF_WP                        (MODULE_BASE+0x428)
#define     MODULE_STAT                  (MODULE_BASE+0x440)
#define     ISP_DEBUG                    (MODULE_BASE+0x450)

/*---------CSI0 Register Address--*/
#define     CSI0_BASE                    0xE02d0000
#define     CSI0_CTRL                    (CSI0_BASE+0x00)
#define     CSI0_SHORT_PACKET            (CSI0_BASE+0x04)
#define     CSI0_ERROR_PENDING           (CSI0_BASE+0x08)
#define     CSI0_STATUS_PENDING          (CSI0_BASE+0x0c)
#define     CSI0_LANE_STATUS             (CSI0_BASE+0x10)
#define     CSI0_PHY_T0                  (CSI0_BASE+0x14)
#define     CSI0_PHY_T1                  (CSI0_BASE+0x18)
#define     CSI0_PHY_T2                  (CSI0_BASE+0x1c)
#define     CSI0_ANALOG_PHY              (CSI0_BASE+0x20)
#define     CSI0_PH                      (CSI0_BASE+0x24)
#define     CSI0_PIN_MAP                 (CSI0_BASE+0x28)
#define     CSI0_CONTEXT_CFG             (CSI0_BASE+0x100)
#define     CSI0_CONTEXT_STATUS          (CSI0_BASE+0x104)

/*-------CSI1 Register Address--*/
#define     CSI1_BASE                    0xE02d8000
#define     CSI1_CTRL                    (CSI1_BASE+0x00)
#define     CSI1_SHORT_PACKET            (CSI1_BASE+0x04)
#define     CSI1_ERROR_PENDING           (CSI1_BASE+0x08)
#define     CSI1_STATUS_PENDING          (CSI1_BASE+0x0c)
#define     CSI1_LANE_STATUS             (CSI1_BASE+0x10)
#define     CSI1_PHY_T0                  (CSI1_BASE+0x14)
#define     CSI1_PHY_T1                  (CSI1_BASE+0x18)
#define     CSI1_PHY_T2                  (CSI1_BASE+0x1c)
#define     CSI1_ANALOG_PHY              (CSI1_BASE+0x20)
#define     CSI1_PH                      (CSI1_BASE+0x24)
#define     CSI1_PIN_MAP                 (CSI1_BASE+0x28)
#define     CSI1_CONTEXT_CFG             (CSI1_BASE+0x100)
#define     CSI1_CONTEXT_STATUS          (CSI1_BASE+0x104)

/*--------------Other Register Address--*/
#define     DMM_BASE                     0xE0290000
#define     DMM_AXI_NORMAL_PRIORITY      (DMM_BASE+0x002C)
#define     DMM_AXI_BISP_PRIORITY        (DMM_BASE+0x0078)
#define     CMU_BASE                     0xE0160000
#define     CMU_DEVRST0                  (CMU_BASE+0x00A8)

#endif				/* __BISP_REG_H__ */
