/*
* Automatically generated register definition: don't edit
* Spec Version_V1.2
* Sat 07-20-2017  11:44:58
*/
#ifndef __REG_DEFINITION_H___
#define __REG_DEFINITION_H___


//--------------TWI_Controller-------------------------------------------//
//--------------Register Address---------------------------------------//
#define     TWI_CONTROLLER_BASE                                               0xF0
#define     SADDR                                                             (TWI_CONTROLLER_BASE+0x00)

//--------------Bits Location------------------------------------------//
#define     SADDR_SDA_E                                                       7
#define     SADDR_SDA_SHIFT                                                   1
#define     SADDR_SDA_MASK                                                    (0x7F<<1)
#define     SADDR_FCS                                                         0

//--------------Audio_Interface_Controller-------------------------------------------//
//--------------Register Address---------------------------------------//
#define     AUDIO_INTERFACE_CONTROLLER_BASE                                   0x00
#define     AUDIOIF_CTL                                                       (AUDIO_INTERFACE_CONTROLLER_BASE+0x00)
#define     AUDIOIF_DBGCTL                                                    (AUDIO_INTERFACE_CONTROLLER_BASE+0x01)
#define     MIC_CTL0                                                          (AUDIO_INTERFACE_CONTROLLER_BASE+0x02)
#define     MIC_CTL1                                                          (AUDIO_INTERFACE_CONTROLLER_BASE+0x03)
#define     CH0_DIG_CTL                                                       (AUDIO_INTERFACE_CONTROLLER_BASE+0x04)
#define     ADC0_ANA_CTL0                                                     (AUDIO_INTERFACE_CONTROLLER_BASE+0x05)
#define     ADC0_ANA_CTL1                                                     (AUDIO_INTERFACE_CONTROLLER_BASE+0x06)
#define     CH1_DIG_CTL                                                       (AUDIO_INTERFACE_CONTROLLER_BASE+0x07)
#define     ADC1_ANA_CTL0                                                     (AUDIO_INTERFACE_CONTROLLER_BASE+0x08)
#define     ADC1_ANA_CTL1                                                     (AUDIO_INTERFACE_CONTROLLER_BASE+0x09)
#define     CH2_DIG_CTL                                                       (AUDIO_INTERFACE_CONTROLLER_BASE+0x0a)
#define     ADC2_ANA_CTL0                                                     (AUDIO_INTERFACE_CONTROLLER_BASE+0x0b)
#define     ADC2_ANA_CTL1                                                     (AUDIO_INTERFACE_CONTROLLER_BASE+0x0c)
#define     CH3_DIG_CTL                                                       (AUDIO_INTERFACE_CONTROLLER_BASE+0x0d)
#define     ADC3_ANA_CTL0                                                     (AUDIO_INTERFACE_CONTROLLER_BASE+0x0e)
#define     ADC3_ANA_CTL1                                                     (AUDIO_INTERFACE_CONTROLLER_BASE+0x0f)
#define     CH4_DIG_CTL                                                       (AUDIO_INTERFACE_CONTROLLER_BASE+0x10)
#define     ADC4_ANA_CTL0                                                     (AUDIO_INTERFACE_CONTROLLER_BASE+0x11)
#define     ADC4_ANA_CTL1                                                     (AUDIO_INTERFACE_CONTROLLER_BASE+0x12)
#define     CH5_DIG_CTL                                                       (AUDIO_INTERFACE_CONTROLLER_BASE+0x13)
#define     ADC5_ANA_CTL0                                                     (AUDIO_INTERFACE_CONTROLLER_BASE+0x14)
#define     ADC5_ANA_CTL1                                                     (AUDIO_INTERFACE_CONTROLLER_BASE+0x15)
#define     CH6_DIG_CTL                                                       (AUDIO_INTERFACE_CONTROLLER_BASE+0x16)
#define     ADC6_ANA_CTL0                                                     (AUDIO_INTERFACE_CONTROLLER_BASE+0x17)
#define     ADC6_ANA_CTL1                                                     (AUDIO_INTERFACE_CONTROLLER_BASE+0x18)
#define     CH7_DIG_CTL                                                       (AUDIO_INTERFACE_CONTROLLER_BASE+0x19)
#define     ADC7_ANA_CTL0                                                     (AUDIO_INTERFACE_CONTROLLER_BASE+0x1a)
#define     ADC7_ANA_CTL1                                                     (AUDIO_INTERFACE_CONTROLLER_BASE+0x1b)
#define     MICBIAS_CTL0                                                      (AUDIO_INTERFACE_CONTROLLER_BASE+0x1c)
#define     MICBIAS_CTL1                                                      (AUDIO_INTERFACE_CONTROLLER_BASE+0x1d)
#define     MICBIAS_CTL2                                                      (AUDIO_INTERFACE_CONTROLLER_BASE+0x1e)
#define     MICBIAS_CTL3                                                      (AUDIO_INTERFACE_CONTROLLER_BASE+0x1f)
#define     ADC_VREF_CTL                                                      (AUDIO_INTERFACE_CONTROLLER_BASE+0x20)
#define     VAD_CTL                                                           (AUDIO_INTERFACE_CONTROLLER_BASE+0x21)
#define     VAD_THRESHOLD                                                     (AUDIO_INTERFACE_CONTROLLER_BASE+0x22)
#define     VAD_SPEED                                                         (AUDIO_INTERFACE_CONTROLLER_BASE+0x23)
#define     VAD_DETVAL                                                        (AUDIO_INTERFACE_CONTROLLER_BASE+0x25)

//--------------Bits Location------------------------------------------//
#define     AUDIOIF_CTL_SPI_NSS_CTL                                           12
#define     AUDIOIF_CTL_I2STX_BCLK_OUT_DELAY_E                                11
#define     AUDIOIF_CTL_I2STX_BCLK_OUT_DELAY_SHIFT                            9
#define     AUDIOIF_CTL_I2STX_BCLK_OUT_DELAY_MASK                             (0x7<<9)
#define     AUDIOIF_CTL_I2STX_SYNC_MODE_E                                     8
#define     AUDIOIF_CTL_I2STX_SYNC_MODE_SHIFT                                 7
#define     AUDIOIF_CTL_I2STX_SYNC_MODE_MASK                                  (0x3<<7)
#define     AUDIOIF_CTL_I2STX_TYPE_E                                          6
#define     AUDIOIF_CTL_I2STX_TYPE_SHIFT                                      5
#define     AUDIOIF_CTL_I2STX_TYPE_MASK                                       (0x3<<5)
#define     AUDIOIF_CTL_AUDIO_IF_DEV_MODE                                     4
#define     AUDIOIF_CTL_AUDIO_IF_CH_SET_E                                     3
#define     AUDIOIF_CTL_AUDIO_IF_CH_SET_SHIFT                                 2
#define     AUDIOIF_CTL_AUDIO_IF_CH_SET_MASK                                  (0x3<<2)
#define     AUDIOIF_CTL_AUDIO_IF_XFER_CHID                                    1
#define     AUDIOIF_CTL_AUDIO_IF_EN                                           0

#define     AUDIOIF_DBGCTL_DEBUG_CH_SEL_E                                     4
#define     AUDIOIF_DBGCTL_DEBUG_CH_SEL_SHIFT                                 2
#define     AUDIOIF_DBGCTL_DEBUG_CH_SEL_MASK                                  (0x7<<2)
#define     AUDIOIF_DBGCTL_ADC_ANA_DBG_EN                                     1
#define     AUDIOIF_DBGCTL_CH_DIG_DBG_EN                                      0

#define     MIC_CTL0_DMIC_OVFS_SEL                                            14
#define     MIC_CTL0_DMIC_PRE_GAIN_E                                          13
#define     MIC_CTL0_DMIC_PRE_GAIN_SHIFT                                      12
#define     MIC_CTL0_DMIC_PRE_GAIN_MASK                                       (0x3<<12)
#define     MIC_CTL0_CH3_MAP_E                                                11
#define     MIC_CTL0_CH3_MAP_SHIFT                                            9
#define     MIC_CTL0_CH3_MAP_MASK                                             (0x7<<9)
#define     MIC_CTL0_CH2_MAP_E                                                8
#define     MIC_CTL0_CH2_MAP_SHIFT                                            6
#define     MIC_CTL0_CH2_MAP_MASK                                             (0x7<<6)
#define     MIC_CTL0_CH1_MAP_E                                                5
#define     MIC_CTL0_CH1_MAP_SHIFT                                            3
#define     MIC_CTL0_CH1_MAP_MASK                                             (0x7<<3)
#define     MIC_CTL0_CH0_MAP_E                                                2
#define     MIC_CTL0_CH0_MAP_SHIFT                                            0
#define     MIC_CTL0_CH0_MAP_MASK                                             (0x7<<0)

#define     MIC_CTL1_CH7_MAP_E                                                11
#define     MIC_CTL1_CH7_MAP_SHIFT                                            9
#define     MIC_CTL1_CH7_MAP_MASK                                             (0x7<<9)
#define     MIC_CTL1_CH6_MAP_E                                                8
#define     MIC_CTL1_CH6_MAP_SHIFT                                            6
#define     MIC_CTL1_CH6_MAP_MASK                                             (0x7<<6)
#define     MIC_CTL1_CH5_MAP_E                                                5
#define     MIC_CTL1_CH5_MAP_SHIFT                                            3
#define     MIC_CTL1_CH5_MAP_MASK                                             (0x7<<3)
#define     MIC_CTL1_CH4_MAP_E                                                2
#define     MIC_CTL1_CH4_MAP_SHIFT                                            0
#define     MIC_CTL1_CH4_MAP_MASK                                             (0x7<<0)

#define     CH0_DIG_CTL_MIC_SEL                                               14
#define     CH0_DIG_CTL_CH0_HPF_EN                                            13
#define     CH0_DIG_CTL_CH0_ZERO_CROSS_EN                                     12
#define     CH0_DIG_CTL_CH0_SGAIN_E                                           11
#define     CH0_DIG_CTL_CH0_SGAIN_SHIFT                                       9
#define     CH0_DIG_CTL_CH0_SGAIN_MASK                                        (0x7<<9)
#define     CH0_DIG_CTL_CH0_CGAIN_E                                           8
#define     CH0_DIG_CTL_CH0_CGAIN_SHIFT                                       7
#define     CH0_DIG_CTL_CH0_CGAIN_MASK                                        (0x3<<7)
#define     CH0_DIG_CTL_CH0_FGAIN_E                                           6
#define     CH0_DIG_CTL_CH0_FGAIN_SHIFT                                       1
#define     CH0_DIG_CTL_CH0_FGAIN_MASK                                        (0x3F<<1)
#define     CH0_DIG_CTL_CH0_DIG_EN                                            0

#define     ADC0_ANA_CTL0_BIASBOOSTEN                                         15
#define     ADC0_ANA_CTL0_COMPIB_E                                            14
#define     ADC0_ANA_CTL0_COMPIB_SHIFT                                        13
#define     ADC0_ANA_CTL0_COMPIB_MASK                                         (0x3<<13)
#define     ADC0_ANA_CTL0_MICOPIB_E                                           12
#define     ADC0_ANA_CTL0_MICOPIB_SHIFT                                       11
#define     ADC0_ANA_CTL0_MICOPIB_MASK                                        (0x3<<11)
#define     ADC0_ANA_CTL0_MICBUFIB_E                                          10
#define     ADC0_ANA_CTL0_MICBUFIB_SHIFT                                      9
#define     ADC0_ANA_CTL0_MICBUFIB_MASK                                       (0x3<<9)
#define     ADC0_ANA_CTL0_SDMOPSUMIB_E                                        8
#define     ADC0_ANA_CTL0_SDMOPSUMIB_SHIFT                                    7
#define     ADC0_ANA_CTL0_SDMOPSUMIB_MASK                                     (0x3<<7)
#define     ADC0_ANA_CTL0_SDMOP3IB_E                                          6
#define     ADC0_ANA_CTL0_SDMOP3IB_SHIFT                                      5
#define     ADC0_ANA_CTL0_SDMOP3IB_MASK                                       (0x3<<5)
#define     ADC0_ANA_CTL0_SDMOP2IB_E                                          4
#define     ADC0_ANA_CTL0_SDMOP2IB_SHIFT                                      3
#define     ADC0_ANA_CTL0_SDMOP2IB_MASK                                       (0x3<<3)
#define     ADC0_ANA_CTL0_SDMOP1IB_E                                          2
#define     ADC0_ANA_CTL0_SDMOP1IB_SHIFT                                      0
#define     ADC0_ANA_CTL0_SDMOP1IB_MASK                                       (0x7<<0)

#define     ADC0_ANA_CTL1_BIASEN                                              15
#define     ADC0_ANA_CTL1_DITHEN                                              14
#define     ADC0_ANA_CTL1_DITHSET_E                                           13
#define     ADC0_ANA_CTL1_DITHSET_SHIFT                                       12
#define     ADC0_ANA_CTL1_DITHSET_MASK                                        (0x3<<12)
#define     ADC0_ANA_CTL1_DEMEN                                               11
#define     ADC0_ANA_CTL1_ADCEN                                               10
#define     ADC0_ANA_CTL1_INCEN                                               9
#define     ADC0_ANA_CTL1_MICOPEN                                             8
#define     ADC0_ANA_CTL1_FDBUFEN                                             7
#define     ADC0_ANA_CTL1_MICOPIQS_E                                          6
#define     ADC0_ANA_CTL1_MICOPIQS_SHIFT                                      5
#define     ADC0_ANA_CTL1_MICOPIQS_MASK                                       (0x3<<5)
#define     ADC0_ANA_CTL1_MICGBEN                                             4
#define     ADC0_ANA_CTL1_GAINC_E                                             3
#define     ADC0_ANA_CTL1_GAINC_SHIFT                                         0
#define     ADC0_ANA_CTL1_GAINC_MASK                                          (0xF<<0)

#define     CH1_DIG_CTL_MIC_SEL                                               14
#define     CH1_DIG_CTL_CH1_HPF_EN                                            13
#define     CH1_DIG_CTL_CH1_ZERO_CROSS_EN                                     12
#define     CH1_DIG_CTL_CH1_SGAIN_E                                           11
#define     CH1_DIG_CTL_CH1_SGAIN_SHIFT                                       9
#define     CH1_DIG_CTL_CH1_SGAIN_MASK                                        (0x7<<9)
#define     CH1_DIG_CTL_CH1_CGAIN_E                                           8
#define     CH1_DIG_CTL_CH1_CGAIN_SHIFT                                       7
#define     CH1_DIG_CTL_CH1_CGAIN_MASK                                        (0x3<<7)
#define     CH1_DIG_CTL_CH1_FGAIN_E                                           6
#define     CH1_DIG_CTL_CH1_FGAIN_SHIFT                                       1
#define     CH1_DIG_CTL_CH1_FGAIN_MASK                                        (0x3F<<1)
#define     CH1_DIG_CTL_CH1_DIG_EN                                            0

#define     ADC1_ANA_CTL0_BIASBOOSTEN                                         15
#define     ADC1_ANA_CTL0_COMPIB_E                                            14
#define     ADC1_ANA_CTL0_COMPIB_SHIFT                                        13
#define     ADC1_ANA_CTL0_COMPIB_MASK                                         (0x3<<13)
#define     ADC1_ANA_CTL0_MICOPIB_E                                           12
#define     ADC1_ANA_CTL0_MICOPIB_SHIFT                                       11
#define     ADC1_ANA_CTL0_MICOPIB_MASK                                        (0x3<<11)
#define     ADC1_ANA_CTL0_MICBUFIB_E                                          10
#define     ADC1_ANA_CTL0_MICBUFIB_SHIFT                                      9
#define     ADC1_ANA_CTL0_MICBUFIB_MASK                                       (0x3<<9)
#define     ADC1_ANA_CTL0_SDMOPSUMIB_E                                        8
#define     ADC1_ANA_CTL0_SDMOPSUMIB_SHIFT                                    7
#define     ADC1_ANA_CTL0_SDMOPSUMIB_MASK                                     (0x3<<7)
#define     ADC1_ANA_CTL0_SDMOP3IB_E                                          6
#define     ADC1_ANA_CTL0_SDMOP3IB_SHIFT                                      5
#define     ADC1_ANA_CTL0_SDMOP3IB_MASK                                       (0x3<<5)
#define     ADC1_ANA_CTL0_SDMOP2IB_E                                          4
#define     ADC1_ANA_CTL0_SDMOP2IB_SHIFT                                      3
#define     ADC1_ANA_CTL0_SDMOP2IB_MASK                                       (0x3<<3)
#define     ADC1_ANA_CTL0_SDMOP1IB_E                                          2
#define     ADC1_ANA_CTL0_SDMOP1IB_SHIFT                                      0
#define     ADC1_ANA_CTL0_SDMOP1IB_MASK                                       (0x7<<0)

#define     ADC1_ANA_CTL1_BIASEN                                              15
#define     ADC1_ANA_CTL1_DITHEN                                              14
#define     ADC1_ANA_CTL1_DITHSET_E                                           13
#define     ADC1_ANA_CTL1_DITHSET_SHIFT                                       12
#define     ADC1_ANA_CTL1_DITHSET_MASK                                        (0x3<<12)
#define     ADC1_ANA_CTL1_DEMEN                                               11
#define     ADC1_ANA_CTL1_ADCEN                                               10
#define     ADC1_ANA_CTL1_INCEN                                               9
#define     ADC1_ANA_CTL1_MICOPEN                                             8
#define     ADC1_ANA_CTL1_FDBUFEN                                             7
#define     ADC1_ANA_CTL1_MICOPIQS_E                                          6
#define     ADC1_ANA_CTL1_MICOPIQS_SHIFT                                      5
#define     ADC1_ANA_CTL1_MICOPIQS_MASK                                       (0x3<<5)
#define     ADC1_ANA_CTL1_MICGBEN                                             4
#define     ADC1_ANA_CTL1_GAINC_E                                             3
#define     ADC1_ANA_CTL1_GAINC_SHIFT                                         0
#define     ADC1_ANA_CTL1_GAINC_MASK                                          (0xF<<0)

#define     CH2_DIG_CTL_MIC_SEL                                               14
#define     CH2_DIG_CTL_CH2_HPF_EN                                            13
#define     CH2_DIG_CTL_CH2_ZERO_CROSS_EN                                     12
#define     CH2_DIG_CTL_CH2_SGAIN_E                                           11
#define     CH2_DIG_CTL_CH2_SGAIN_SHIFT                                       9
#define     CH2_DIG_CTL_CH2_SGAIN_MASK                                        (0x7<<9)
#define     CH2_DIG_CTL_CH2_CGAIN_E                                           8
#define     CH2_DIG_CTL_CH2_CGAIN_SHIFT                                       7
#define     CH2_DIG_CTL_CH2_CGAIN_MASK                                        (0x3<<7)
#define     CH2_DIG_CTL_CH2_FGAIN_E                                           6
#define     CH2_DIG_CTL_CH2_FGAIN_SHIFT                                       1
#define     CH2_DIG_CTL_CH2_FGAIN_MASK                                        (0x3F<<1)
#define     CH2_DIG_CTL_CH2_DIG_EN                                            0

#define     ADC2_ANA_CTL0_BIASBOOSTEN                                         15
#define     ADC2_ANA_CTL0_COMPIB_E                                            14
#define     ADC2_ANA_CTL0_COMPIB_SHIFT                                        13
#define     ADC2_ANA_CTL0_COMPIB_MASK                                         (0x3<<13)
#define     ADC2_ANA_CTL0_MICOPIB_E                                           12
#define     ADC2_ANA_CTL0_MICOPIB_SHIFT                                       11
#define     ADC2_ANA_CTL0_MICOPIB_MASK                                        (0x3<<11)
#define     ADC2_ANA_CTL0_MICBUFIB_E                                          10
#define     ADC2_ANA_CTL0_MICBUFIB_SHIFT                                      9
#define     ADC2_ANA_CTL0_MICBUFIB_MASK                                       (0x3<<9)
#define     ADC2_ANA_CTL0_SDMOPSUMIB_E                                        8
#define     ADC2_ANA_CTL0_SDMOPSUMIB_SHIFT                                    7
#define     ADC2_ANA_CTL0_SDMOPSUMIB_MASK                                     (0x3<<7)
#define     ADC2_ANA_CTL0_SDMOP3IB_E                                          6
#define     ADC2_ANA_CTL0_SDMOP3IB_SHIFT                                      5
#define     ADC2_ANA_CTL0_SDMOP3IB_MASK                                       (0x3<<5)
#define     ADC2_ANA_CTL0_SDMOP2IB_E                                          4
#define     ADC2_ANA_CTL0_SDMOP2IB_SHIFT                                      3
#define     ADC2_ANA_CTL0_SDMOP2IB_MASK                                       (0x3<<3)
#define     ADC2_ANA_CTL0_SDMOP1IB_E                                          2
#define     ADC2_ANA_CTL0_SDMOP1IB_SHIFT                                      0
#define     ADC2_ANA_CTL0_SDMOP1IB_MASK                                       (0x7<<0)

#define     ADC2_ANA_CTL1_BIASEN                                              15
#define     ADC2_ANA_CTL1_DITHEN                                              14
#define     ADC2_ANA_CTL1_DITHSET_E                                           13
#define     ADC2_ANA_CTL1_DITHSET_SHIFT                                       12
#define     ADC2_ANA_CTL1_DITHSET_MASK                                        (0x3<<12)
#define     ADC2_ANA_CTL1_DEMEN                                               11
#define     ADC2_ANA_CTL1_ADCEN                                               10
#define     ADC2_ANA_CTL1_INCEN                                               9
#define     ADC2_ANA_CTL1_MICOPEN                                             8
#define     ADC2_ANA_CTL1_FDBUFEN                                             7
#define     ADC2_ANA_CTL1_MICOPIQS_E                                          6
#define     ADC2_ANA_CTL1_MICOPIQS_SHIFT                                      5
#define     ADC2_ANA_CTL1_MICOPIQS_MASK                                       (0x3<<5)
#define     ADC2_ANA_CTL1_MICGBEN                                             4
#define     ADC2_ANA_CTL1_GAINC_E                                             3
#define     ADC2_ANA_CTL1_GAINC_SHIFT                                         0
#define     ADC2_ANA_CTL1_GAINC_MASK                                          (0xF<<0)

#define     CH3_DIG_CTL_MIC_SEL                                               14
#define     CH3_DIG_CTL_CH3_HPF_EN                                            13
#define     CH3_DIG_CTL_CH3_ZERO_CROSS_EN                                     12
#define     CH3_DIG_CTL_CH3_SGAIN_E                                           11
#define     CH3_DIG_CTL_CH3_SGAIN_SHIFT                                       9
#define     CH3_DIG_CTL_CH3_SGAIN_MASK                                        (0x7<<9)
#define     CH3_DIG_CTL_CH3_CGAIN_E                                           8
#define     CH3_DIG_CTL_CH3_CGAIN_SHIFT                                       7
#define     CH3_DIG_CTL_CH3_CGAIN_MASK                                        (0x3<<7)
#define     CH3_DIG_CTL_CH3_FGAIN_E                                           6
#define     CH3_DIG_CTL_CH3_FGAIN_SHIFT                                       1
#define     CH3_DIG_CTL_CH3_FGAIN_MASK                                        (0x3F<<1)
#define     CH3_DIG_CTL_CH3_DIG_EN                                            0

#define     ADC3_ANA_CTL0_BIASBOOSTEN                                         15
#define     ADC3_ANA_CTL0_COMPIB_E                                            14
#define     ADC3_ANA_CTL0_COMPIB_SHIFT                                        13
#define     ADC3_ANA_CTL0_COMPIB_MASK                                         (0x3<<13)
#define     ADC3_ANA_CTL0_MICOPIB_E                                           12
#define     ADC3_ANA_CTL0_MICOPIB_SHIFT                                       11
#define     ADC3_ANA_CTL0_MICOPIB_MASK                                        (0x3<<11)
#define     ADC3_ANA_CTL0_MICBUFIB_E                                          10
#define     ADC3_ANA_CTL0_MICBUFIB_SHIFT                                      9
#define     ADC3_ANA_CTL0_MICBUFIB_MASK                                       (0x3<<9)
#define     ADC3_ANA_CTL0_SDMOPSUMIB_E                                        8
#define     ADC3_ANA_CTL0_SDMOPSUMIB_SHIFT                                    7
#define     ADC3_ANA_CTL0_SDMOPSUMIB_MASK                                     (0x3<<7)
#define     ADC3_ANA_CTL0_SDMOP3IB_E                                          6
#define     ADC3_ANA_CTL0_SDMOP3IB_SHIFT                                      5
#define     ADC3_ANA_CTL0_SDMOP3IB_MASK                                       (0x3<<5)
#define     ADC3_ANA_CTL0_SDMOP2IB_E                                          4
#define     ADC3_ANA_CTL0_SDMOP2IB_SHIFT                                      3
#define     ADC3_ANA_CTL0_SDMOP2IB_MASK                                       (0x3<<3)
#define     ADC3_ANA_CTL0_SDMOP1IB_E                                          2
#define     ADC3_ANA_CTL0_SDMOP1IB_SHIFT                                      0
#define     ADC3_ANA_CTL0_SDMOP1IB_MASK                                       (0x7<<0)

#define     ADC3_ANA_CTL1_BIASEN                                              15
#define     ADC3_ANA_CTL1_DITHEN                                              14
#define     ADC3_ANA_CTL1_DITHSET_E                                           13
#define     ADC3_ANA_CTL1_DITHSET_SHIFT                                       12
#define     ADC3_ANA_CTL1_DITHSET_MASK                                        (0x3<<12)
#define     ADC3_ANA_CTL1_DEMEN                                               11
#define     ADC3_ANA_CTL1_ADCEN                                               10
#define     ADC3_ANA_CTL1_INCEN                                               9
#define     ADC3_ANA_CTL1_MICOPEN                                             8
#define     ADC3_ANA_CTL1_FDBUFEN                                             7
#define     ADC3_ANA_CTL1_MICOPIQS_E                                          6
#define     ADC3_ANA_CTL1_MICOPIQS_SHIFT                                      5
#define     ADC3_ANA_CTL1_MICOPIQS_MASK                                       (0x3<<5)
#define     ADC3_ANA_CTL1_MICGBEN                                             4
#define     ADC3_ANA_CTL1_GAINC_E                                             3
#define     ADC3_ANA_CTL1_GAINC_SHIFT                                         0
#define     ADC3_ANA_CTL1_GAINC_MASK                                          (0xF<<0)

#define     CH4_DIG_CTL_MIC_SEL                                               14
#define     CH4_DIG_CTL_CH4_HPF_EN                                            13
#define     CH4_DIG_CTL_CH4_ZERO_CROSS_EN                                     12
#define     CH4_DIG_CTL_CH4_SGAIN_E                                           11
#define     CH4_DIG_CTL_CH4_SGAIN_SHIFT                                       9
#define     CH4_DIG_CTL_CH4_SGAIN_MASK                                        (0x7<<9)
#define     CH4_DIG_CTL_CH4_CGAIN_E                                           8
#define     CH4_DIG_CTL_CH4_CGAIN_SHIFT                                       7
#define     CH4_DIG_CTL_CH4_CGAIN_MASK                                        (0x3<<7)
#define     CH4_DIG_CTL_CH4_FGAIN_E                                           6
#define     CH4_DIG_CTL_CH4_FGAIN_SHIFT                                       1
#define     CH4_DIG_CTL_CH4_FGAIN_MASK                                        (0x3F<<1)
#define     CH4_DIG_CTL_CH4_DIG_EN                                            0

#define     ADC4_ANA_CTL0_BIASBOOSTEN                                         15
#define     ADC4_ANA_CTL0_COMPIB_E                                            14
#define     ADC4_ANA_CTL0_COMPIB_SHIFT                                        13
#define     ADC4_ANA_CTL0_COMPIB_MASK                                         (0x3<<13)
#define     ADC4_ANA_CTL0_MICOPIB_E                                           12
#define     ADC4_ANA_CTL0_MICOPIB_SHIFT                                       11
#define     ADC4_ANA_CTL0_MICOPIB_MASK                                        (0x3<<11)
#define     ADC4_ANA_CTL0_MICBUFIB_E                                          10
#define     ADC4_ANA_CTL0_MICBUFIB_SHIFT                                      9
#define     ADC4_ANA_CTL0_MICBUFIB_MASK                                       (0x3<<9)
#define     ADC4_ANA_CTL0_SDMOPSUMIB_E                                        8
#define     ADC4_ANA_CTL0_SDMOPSUMIB_SHIFT                                    7
#define     ADC4_ANA_CTL0_SDMOPSUMIB_MASK                                     (0x3<<7)
#define     ADC4_ANA_CTL0_SDMOP3IB_E                                          6
#define     ADC4_ANA_CTL0_SDMOP3IB_SHIFT                                      5
#define     ADC4_ANA_CTL0_SDMOP3IB_MASK                                       (0x3<<5)
#define     ADC4_ANA_CTL0_SDMOP2IB_E                                          4
#define     ADC4_ANA_CTL0_SDMOP2IB_SHIFT                                      3
#define     ADC4_ANA_CTL0_SDMOP2IB_MASK                                       (0x3<<3)
#define     ADC4_ANA_CTL0_SDMOP1IB_E                                          2
#define     ADC4_ANA_CTL0_SDMOP1IB_SHIFT                                      0
#define     ADC4_ANA_CTL0_SDMOP1IB_MASK                                       (0x7<<0)

#define     ADC4_ANA_CTL1_BIASEN                                              15
#define     ADC4_ANA_CTL1_DITHEN                                              14
#define     ADC4_ANA_CTL1_DITHSET_E                                           13
#define     ADC4_ANA_CTL1_DITHSET_SHIFT                                       12
#define     ADC4_ANA_CTL1_DITHSET_MASK                                        (0x3<<12)
#define     ADC4_ANA_CTL1_DEMEN                                               11
#define     ADC4_ANA_CTL1_ADCEN                                               10
#define     ADC4_ANA_CTL1_INCEN                                               9
#define     ADC4_ANA_CTL1_MICOPEN                                             8
#define     ADC4_ANA_CTL1_FDBUFEN                                             7
#define     ADC4_ANA_CTL1_MICOPIQS_E                                          6
#define     ADC4_ANA_CTL1_MICOPIQS_SHIFT                                      5
#define     ADC4_ANA_CTL1_MICOPIQS_MASK                                       (0x3<<5)
#define     ADC4_ANA_CTL1_MICGBEN                                             4
#define     ADC4_ANA_CTL1_GAINC_E                                             3
#define     ADC4_ANA_CTL1_GAINC_SHIFT                                         0
#define     ADC4_ANA_CTL1_GAINC_MASK                                          (0xF<<0)

#define     CH5_DIG_CTL_MIC_SEL                                               14
#define     CH5_DIG_CTL_CH5_HPF_EN                                            13
#define     CH5_DIG_CTL_CH5_ZERO_CROSS_EN                                     12
#define     CH5_DIG_CTL_CH5_SGAIN_E                                           11
#define     CH5_DIG_CTL_CH5_SGAIN_SHIFT                                       9
#define     CH5_DIG_CTL_CH5_SGAIN_MASK                                        (0x7<<9)
#define     CH5_DIG_CTL_CH5_CGAIN_E                                           8
#define     CH5_DIG_CTL_CH5_CGAIN_SHIFT                                       7
#define     CH5_DIG_CTL_CH5_CGAIN_MASK                                        (0x3<<7)
#define     CH5_DIG_CTL_CH5_FGAIN_E                                           6
#define     CH5_DIG_CTL_CH5_FGAIN_SHIFT                                       1
#define     CH5_DIG_CTL_CH5_FGAIN_MASK                                        (0x3F<<1)
#define     CH5_DIG_CTL_CH5_DIG_EN                                            0

#define     ADC5_ANA_CTL0_BIASBOOSTEN                                         15
#define     ADC5_ANA_CTL0_COMPIB_E                                            14
#define     ADC5_ANA_CTL0_COMPIB_SHIFT                                        13
#define     ADC5_ANA_CTL0_COMPIB_MASK                                         (0x3<<13)
#define     ADC5_ANA_CTL0_MICOPIB_E                                           12
#define     ADC5_ANA_CTL0_MICOPIB_SHIFT                                       11
#define     ADC5_ANA_CTL0_MICOPIB_MASK                                        (0x3<<11)
#define     ADC5_ANA_CTL0_MICBUFIB_E                                          10
#define     ADC5_ANA_CTL0_MICBUFIB_SHIFT                                      9
#define     ADC5_ANA_CTL0_MICBUFIB_MASK                                       (0x3<<9)
#define     ADC5_ANA_CTL0_SDMOPSUMIB_E                                        8
#define     ADC5_ANA_CTL0_SDMOPSUMIB_SHIFT                                    7
#define     ADC5_ANA_CTL0_SDMOPSUMIB_MASK                                     (0x3<<7)
#define     ADC5_ANA_CTL0_SDMOP3IB_E                                          6
#define     ADC5_ANA_CTL0_SDMOP3IB_SHIFT                                      5
#define     ADC5_ANA_CTL0_SDMOP3IB_MASK                                       (0x3<<5)
#define     ADC5_ANA_CTL0_SDMOP2IB_E                                          4
#define     ADC5_ANA_CTL0_SDMOP2IB_SHIFT                                      3
#define     ADC5_ANA_CTL0_SDMOP2IB_MASK                                       (0x3<<3)
#define     ADC5_ANA_CTL0_SDMOP1IB_E                                          2
#define     ADC5_ANA_CTL0_SDMOP1IB_SHIFT                                      0
#define     ADC5_ANA_CTL0_SDMOP1IB_MASK                                       (0x7<<0)

#define     ADC5_ANA_CTL1_BIASEN                                              15
#define     ADC5_ANA_CTL1_DITHEN                                              14
#define     ADC5_ANA_CTL1_DITHSET_E                                           13
#define     ADC5_ANA_CTL1_DITHSET_SHIFT                                       12
#define     ADC5_ANA_CTL1_DITHSET_MASK                                        (0x3<<12)
#define     ADC5_ANA_CTL1_DEMEN                                               11
#define     ADC5_ANA_CTL1_ADCEN                                               10
#define     ADC5_ANA_CTL1_INCEN                                               9
#define     ADC5_ANA_CTL1_MICOPEN                                             8
#define     ADC5_ANA_CTL1_FDBUFEN                                             7
#define     ADC5_ANA_CTL1_MICOPIQS_E                                          6
#define     ADC5_ANA_CTL1_MICOPIQS_SHIFT                                      5
#define     ADC5_ANA_CTL1_MICOPIQS_MASK                                       (0x3<<5)
#define     ADC5_ANA_CTL1_MICGBEN                                             4
#define     ADC5_ANA_CTL1_GAINC_E                                             3
#define     ADC5_ANA_CTL1_GAINC_SHIFT                                         0
#define     ADC5_ANA_CTL1_GAINC_MASK                                          (0xF<<0)

#define     CH6_DIG_CTL_MIC_SEL                                               14
#define     CH6_DIG_CTL_CH6_HPF_EN                                            13
#define     CH6_DIG_CTL_CH6_ZERO_CROSS_EN                                     12
#define     CH6_DIG_CTL_CH6_SGAIN_E                                           11
#define     CH6_DIG_CTL_CH6_SGAIN_SHIFT                                       9
#define     CH6_DIG_CTL_CH6_SGAIN_MASK                                        (0x7<<9)
#define     CH6_DIG_CTL_CH6_CGAIN_E                                           8
#define     CH6_DIG_CTL_CH6_CGAIN_SHIFT                                       7
#define     CH6_DIG_CTL_CH6_CGAIN_MASK                                        (0x3<<7)
#define     CH6_DIG_CTL_CH6_FGAIN_E                                           6
#define     CH6_DIG_CTL_CH6_FGAIN_SHIFT                                       1
#define     CH6_DIG_CTL_CH6_FGAIN_MASK                                        (0x3F<<1)
#define     CH6_DIG_CTL_CH6_DIG_EN                                            0

#define     ADC6_ANA_CTL0_BIASBOOSTEN                                         15
#define     ADC6_ANA_CTL0_COMPIB_E                                            14
#define     ADC6_ANA_CTL0_COMPIB_SHIFT                                        13
#define     ADC6_ANA_CTL0_COMPIB_MASK                                         (0x3<<13)
#define     ADC6_ANA_CTL0_MICOPIB_E                                           12
#define     ADC6_ANA_CTL0_MICOPIB_SHIFT                                       11
#define     ADC6_ANA_CTL0_MICOPIB_MASK                                        (0x3<<11)
#define     ADC6_ANA_CTL0_MICBUFIB_E                                          10
#define     ADC6_ANA_CTL0_MICBUFIB_SHIFT                                      9
#define     ADC6_ANA_CTL0_MICBUFIB_MASK                                       (0x3<<9)
#define     ADC6_ANA_CTL0_SDMOPSUMIB_E                                        8
#define     ADC6_ANA_CTL0_SDMOPSUMIB_SHIFT                                    7
#define     ADC6_ANA_CTL0_SDMOPSUMIB_MASK                                     (0x3<<7)
#define     ADC6_ANA_CTL0_SDMOP3IB_E                                          6
#define     ADC6_ANA_CTL0_SDMOP3IB_SHIFT                                      5
#define     ADC6_ANA_CTL0_SDMOP3IB_MASK                                       (0x3<<5)
#define     ADC6_ANA_CTL0_SDMOP2IB_E                                          4
#define     ADC6_ANA_CTL0_SDMOP2IB_SHIFT                                      3
#define     ADC6_ANA_CTL0_SDMOP2IB_MASK                                       (0x3<<3)
#define     ADC6_ANA_CTL0_SDMOP1IB_E                                          2
#define     ADC6_ANA_CTL0_SDMOP1IB_SHIFT                                      0
#define     ADC6_ANA_CTL0_SDMOP1IB_MASK                                       (0x7<<0)

#define     ADC6_ANA_CTL1_BIASEN                                              15
#define     ADC6_ANA_CTL1_DITHEN                                              14
#define     ADC6_ANA_CTL1_DITHSET_E                                           13
#define     ADC6_ANA_CTL1_DITHSET_SHIFT                                       12
#define     ADC6_ANA_CTL1_DITHSET_MASK                                        (0x3<<12)
#define     ADC6_ANA_CTL1_DEMEN                                               11
#define     ADC6_ANA_CTL1_ADCEN                                               10
#define     ADC6_ANA_CTL1_INCEN                                               9
#define     ADC6_ANA_CTL1_MICOPEN                                             8
#define     ADC6_ANA_CTL1_FDBUFEN                                             7
#define     ADC6_ANA_CTL1_MICOPIQS_E                                          6
#define     ADC6_ANA_CTL1_MICOPIQS_SHIFT                                      5
#define     ADC6_ANA_CTL1_MICOPIQS_MASK                                       (0x3<<5)
#define     ADC6_ANA_CTL1_MICGBEN                                             4
#define     ADC6_ANA_CTL1_GAINC_E                                             3
#define     ADC6_ANA_CTL1_GAINC_SHIFT                                         0
#define     ADC6_ANA_CTL1_GAINC_MASK                                          (0xF<<0)

#define     CH7_DIG_CTL_MIC_SEL                                               14
#define     CH7_DIG_CTL_CH7_HPF_EN                                            13
#define     CH7_DIG_CTL_CH7_ZERO_CROSS_EN                                     12
#define     CH7_DIG_CTL_CH7_SGAIN_E                                           11
#define     CH7_DIG_CTL_CH7_SGAIN_SHIFT                                       9
#define     CH7_DIG_CTL_CH7_SGAIN_MASK                                        (0x7<<9)
#define     CH7_DIG_CTL_CH7_CGAIN_E                                           8
#define     CH7_DIG_CTL_CH7_CGAIN_SHIFT                                       7
#define     CH7_DIG_CTL_CH7_CGAIN_MASK                                        (0x3<<7)
#define     CH7_DIG_CTL_CH7_FGAIN_E                                           6
#define     CH7_DIG_CTL_CH7_FGAIN_SHIFT                                       1
#define     CH7_DIG_CTL_CH7_FGAIN_MASK                                        (0x3F<<1)
#define     CH7_DIG_CTL_CH7_DIG_EN                                            0

#define     ADC7_ANA_CTL0_BIASBOOSTEN                                         15
#define     ADC7_ANA_CTL0_COMPIB_E                                            14
#define     ADC7_ANA_CTL0_COMPIB_SHIFT                                        13
#define     ADC7_ANA_CTL0_COMPIB_MASK                                         (0x3<<13)
#define     ADC7_ANA_CTL0_MICOPIB_E                                           12
#define     ADC7_ANA_CTL0_MICOPIB_SHIFT                                       11
#define     ADC7_ANA_CTL0_MICOPIB_MASK                                        (0x3<<11)
#define     ADC7_ANA_CTL0_MICBUFIB_E                                          10
#define     ADC7_ANA_CTL0_MICBUFIB_SHIFT                                      9
#define     ADC7_ANA_CTL0_MICBUFIB_MASK                                       (0x3<<9)
#define     ADC7_ANA_CTL0_SDMOPSUMIB_E                                        8
#define     ADC7_ANA_CTL0_SDMOPSUMIB_SHIFT                                    7
#define     ADC7_ANA_CTL0_SDMOPSUMIB_MASK                                     (0x3<<7)
#define     ADC7_ANA_CTL0_SDMOP3IB_E                                          6
#define     ADC7_ANA_CTL0_SDMOP3IB_SHIFT                                      5
#define     ADC7_ANA_CTL0_SDMOP3IB_MASK                                       (0x3<<5)
#define     ADC7_ANA_CTL0_SDMOP2IB_E                                          4
#define     ADC7_ANA_CTL0_SDMOP2IB_SHIFT                                      3
#define     ADC7_ANA_CTL0_SDMOP2IB_MASK                                       (0x3<<3)
#define     ADC7_ANA_CTL0_SDMOP1IB_E                                          2
#define     ADC7_ANA_CTL0_SDMOP1IB_SHIFT                                      0
#define     ADC7_ANA_CTL0_SDMOP1IB_MASK                                       (0x7<<0)

#define     ADC7_ANA_CTL1_BIASEN                                              15
#define     ADC7_ANA_CTL1_DITHEN                                              14
#define     ADC7_ANA_CTL1_DITHSET_E                                           13
#define     ADC7_ANA_CTL1_DITHSET_SHIFT                                       12
#define     ADC7_ANA_CTL1_DITHSET_MASK                                        (0x3<<12)
#define     ADC7_ANA_CTL1_DEMEN                                               11
#define     ADC7_ANA_CTL1_ADCEN                                               10
#define     ADC7_ANA_CTL1_INCEN                                               9
#define     ADC7_ANA_CTL1_MICOPEN                                             8
#define     ADC7_ANA_CTL1_FDBUFEN                                             7
#define     ADC7_ANA_CTL1_MICOPIQS_E                                          6
#define     ADC7_ANA_CTL1_MICOPIQS_SHIFT                                      5
#define     ADC7_ANA_CTL1_MICOPIQS_MASK                                       (0x3<<5)
#define     ADC7_ANA_CTL1_MICGBEN                                             4
#define     ADC7_ANA_CTL1_GAINC_E                                             3
#define     ADC7_ANA_CTL1_GAINC_SHIFT                                         0
#define     ADC7_ANA_CTL1_GAINC_MASK                                          (0xF<<0)

#define     MICBIAS_CTL0_MICBIAS1BYEN                                         12
#define     MICBIAS_CTL0_MICBIAS1VSET_E                                       11
#define     MICBIAS_CTL0_MICBIAS1VSET_SHIFT                                   9
#define     MICBIAS_CTL0_MICBIAS1VSET_MASK                                    (0x7<<9)
#define     MICBIAS_CTL0_MICBIAS1EN                                           8
#define     MICBIAS_CTL0_ADC0TST_E                                            7
#define     MICBIAS_CTL0_ADC0TST_SHIFT                                        5
#define     MICBIAS_CTL0_ADC0TST_MASK                                         (0x7<<5)
#define     MICBIAS_CTL0_MICBIAS0BYEN                                         4
#define     MICBIAS_CTL0_MICBIAS0VSET_E                                       3
#define     MICBIAS_CTL0_MICBIAS0VSET_SHIFT                                   1
#define     MICBIAS_CTL0_MICBIAS0VSET_MASK                                    (0x7<<1)
#define     MICBIAS_CTL0_MICBIAS0EN                                           0

#define     MICBIAS_CTL1_MICBIAS3BYEN                                         12
#define     MICBIAS_CTL1_MICBIAS3VSET_E                                       11
#define     MICBIAS_CTL1_MICBIAS3VSET_SHIFT                                   9
#define     MICBIAS_CTL1_MICBIAS3VSET_MASK                                    (0x7<<9)
#define     MICBIAS_CTL1_MICBIAS3EN                                           8
#define     MICBIAS_CTL1_MICBIAS2BYEN                                         4
#define     MICBIAS_CTL1_MICBIAS2VSET_E                                       3
#define     MICBIAS_CTL1_MICBIAS2VSET_SHIFT                                   1
#define     MICBIAS_CTL1_MICBIAS2VSET_MASK                                    (0x7<<1)
#define     MICBIAS_CTL1_MICBIAS2EN                                           0

#define     MICBIAS_CTL2_MICBIAS5BYEN                                         12
#define     MICBIAS_CTL2_MICBIAS5VSET_E                                       11
#define     MICBIAS_CTL2_MICBIAS5VSET_SHIFT                                   9
#define     MICBIAS_CTL2_MICBIAS5VSET_MASK                                    (0x7<<9)
#define     MICBIAS_CTL2_MICBIAS5EN                                           8
#define     MICBIAS_CTL2_MICBIAS4BYEN                                         4
#define     MICBIAS_CTL2_MICBIAS4VSET_E                                       3
#define     MICBIAS_CTL2_MICBIAS4VSET_SHIFT                                   1
#define     MICBIAS_CTL2_MICBIAS4VSET_MASK                                    (0x7<<1)
#define     MICBIAS_CTL2_MICBIAS4EN                                           0

#define     MICBIAS_CTL3_MICBIAS7BYEN                                         12
#define     MICBIAS_CTL3_MICBIAS7VSET_E                                       11
#define     MICBIAS_CTL3_MICBIAS7VSET_SHIFT                                   9
#define     MICBIAS_CTL3_MICBIAS7VSET_MASK                                    (0x7<<9)
#define     MICBIAS_CTL3_MICBIAS7EN                                           8
#define     MICBIAS_CTL3_MICBIAS6BYEN                                         4
#define     MICBIAS_CTL3_MICBIAS6VSET_E                                       3
#define     MICBIAS_CTL3_MICBIAS6VSET_SHIFT                                   1
#define     MICBIAS_CTL3_MICBIAS6VSET_MASK                                    (0x7<<1)
#define     MICBIAS_CTL3_MICBIAS6EN                                           0

#define     ADC_VREF_CTL_VRDA_EN                                              15
#define     ADC_VREF_CTL_VRP_CTL_E                                            14
#define     ADC_VREF_CTL_VRP_CTL_SHIFT                                        13
#define     ADC_VREF_CTL_VRP_CTL_MASK                                         (0x3<<13)
#define     ADC_VREF_CTL_VRP_EN                                               12
#define     ADC_VREF_CTL_VRDAOPIB_E                                           11
#define     ADC_VREF_CTL_VRDAOPIB_SHIFT                                       10
#define     ADC_VREF_CTL_VRDAOPIB_MASK                                        (0x3<<10)
#define     ADC_VREF_CTL_VRPOPIB_E                                            9
#define     ADC_VREF_CTL_VRPOPIB_SHIFT                                        8
#define     ADC_VREF_CTL_VRPOPIB_MASK                                         (0x3<<8)
#define     ADC_VREF_CTL_BDG_FILTER                                           6
#define     ADC_VREF_CTL_BDG_PDR                                              5
#define     ADC_VREF_CTL_BDG_CTL_E                                            4
#define     ADC_VREF_CTL_BDG_CTL_SHIFT                                        0
#define     ADC_VREF_CTL_BDG_CTL_MASK                                         (0x1F<<0)

#define     VAD_CTL_PP_CIC_HFP_EN                                             13
#define     VAD_CTL_UPSAMPLECOUNT_E                                           12
#define     VAD_CTL_UPSAMPLECOUNT_SHIFT                                       9
#define     VAD_CTL_UPSAMPLECOUNT_MASK                                        (0xF<<9)
#define     VAD_CTL_VAD_ASR_SEL_E                                             8
#define     VAD_CTL_VAD_ASR_SEL_SHIFT                                         7
#define     VAD_CTL_VAD_ASR_SEL_MASK                                          (0x3<<7)
#define     VAD_CTL_FILTER_D_SEL                                              6
#define     VAD_CTL_VAD_DIG_SEL_E                                             5
#define     VAD_CTL_VAD_DIG_SEL_SHIFT                                         4
#define     VAD_CTL_VAD_DIG_SEL_MASK                                          (0x3<<4)
#define     VAD_CTL_VAD_IP                                                    2
#define     VAD_CTL_VAD_IE                                                    1
#define     VAD_CTL_VAD_EN                                                    0

#define     VAD_THRESHOLD_VAD_TRIGGER_E                                       15
#define     VAD_THRESHOLD_VAD_TRIGGER_SHIFT                                   0
#define     VAD_THRESHOLD_VAD_TRIGGER_MASK                                    (0xFFFF<<0)

#define     VAD_SPEED_VAD_SPEED_E                                             15
#define     VAD_SPEED_VAD_SPEED_SHIFT                                         0
#define     VAD_SPEED_VAD_SPEED_MASK                                          (0xFFFF<<0)

#define     VAD_DETVAL_VAD_DETV_E                                             15
#define     VAD_DETVAL_VAD_DETV_SHIFT                                         0
#define     VAD_DETVAL_VAD_DETV_MASK                                          (0xFFFF<<0)

//--------------CMU_Controller-------------------------------------------//
//--------------Register Address---------------------------------------//
#define     CMU_CONTROLLER_BASE                                               0xA0
#define     CMU_CLKIN_CTL                                                      (CMU_CONTROLLER_BASE+0x00)
#define     CMU_AUDIO_PLL                                                      (CMU_CONTROLLER_BASE+0x01)
#define     CMU_AUDIO_PLLCAL                                                   (CMU_CONTROLLER_BASE+0x02)
#define     CMU_AUDIO_PLLDEBUG                                                 (CMU_CONTROLLER_BASE+0x03)
#define     CMU_CLK_CTL0                                                       (CMU_CONTROLLER_BASE+0x04)
#define     CMU_CLK_CTL1                                                       (CMU_CONTROLLER_BASE+0x05)
#define     CMU_CLK_EN0                                                        (CMU_CONTROLLER_BASE+0x08)
#define     CMU_CLK_EN1                                                        (CMU_CONTROLLER_BASE+0x09)
#define     CMU_DEV_RST                                                        (CMU_CONTROLLER_BASE+0x0A)
#define     CMU_ANALOG_DEBUG                                                   (CMU_CONTROLLER_BASE+0x0B)
#define     CMU_DIGITAL_DEBUG                                                  (CMU_CONTROLLER_BASE+0x0C)
#define     CMU_OSC24M_CAL0                                                   (CMU_CONTROLLER_BASE+0x10)
#define     CMU_OSC24M_CAL1                                                   (CMU_CONTROLLER_BASE+0x11)
#define     CMU_OSC24M_CAL2                                                   (CMU_CONTROLLER_BASE+0x12)
#define     CMU_AVDDLDO_CTL                                                   (CMU_CONTROLLER_BASE+0x13)

//--------------Bits Location------------------------------------------//
#define     CMU_CLKINCTL_CLKIN_DIV                                            8
#define     CMU_CLKINCTL_PADCKIN_EN                                           2
#define     CMU_CLKINCTL_PADCKIN_PD                                           1
#define     CMU_CLKINCTL_HOSC_MODE                                            0

#define     CMU_AUDIOPLL_AUDIOPLL_LPMODE_LPDIVMODE                            15
#define     CMU_AUDIOPLL_AUDIOPLL_LPMODE_INTDIVMODE                           14
#define     CMU_AUDIOPLL_AUDIOPLL_LPMODE_SDMORDER                             13
#define     CMU_AUDIOPLL_AUDIOPLL_LPMODE_FRACDITEN                            12
#define     CMU_AUDIOPLL_AUDIOPLL_LPMODE_DITHER_MODE_E                        11
#define     CMU_AUDIOPLL_AUDIOPLL_LPMODE_DITHER_MODE_SHIFT                    10
#define     CMU_AUDIOPLL_AUDIOPLL_LPMODE_DITHER_MODE_MASK                     (0x3<<10)
#define     CMU_AUDIOPLL_AUDIOPLL_LPMODE_SDM_MOD                              9
#define     CMU_AUDIOPLL_AUDIOPLL_LPMODE_LPF3RD_EN                            8
#define     CMU_AUDIOPLL_AUDIOPLL_MODE_E                                      7
#define     CMU_AUDIOPLL_AUDIOPLL_MODE_SHIFT                                  4
#define     CMU_AUDIOPLL_AUDIOPLL_MODE_MASK                                   (0xF<<4)
#define     CMU_AUDIOPLL_AUDIOPLL_LOCK                                        3
#define     CMU_AUDIOPLL_AUDIOPLL_BYPASS                                      2
#define     CMU_AUDIOPLL_AUDIOPLL_CKIN_MUX                                    1
#define     CMU_AUDIOPLL_AUDIOPLL_EN                                          0

#define     CMU_AUDIOPLLCAL_AUDIOPLL_CTRLWORD_E                               15
#define     CMU_AUDIOPLLCAL_AUDIOPLL_CTRLWORD_SHIFT                           12
#define     CMU_AUDIOPLLCAL_AUDIOPLL_CTRLWORD_MASK                            (0xF<<12)
#define     CMU_AUDIOPLLCAL_AUDIOPLL_CALDONE                                  11
#define     CMU_AUDIOPLLCAL_AUDIOPLL_ICOMCTRL_E                               7
#define     CMU_AUDIOPLLCAL_AUDIOPLL_ICOMCTRL_SHIFT                           4
#define     CMU_AUDIOPLLCAL_AUDIOPLL_ICOMCTRL_MASK                            (0xF<<4)
#define     CMU_AUDIOPLLCAL_AUDIOPLL_ICOMCTRL_SEL                             3
#define     CMU_AUDIOPLLCAL_AUDIOPLL_CALDLY_E                                 2
#define     CMU_AUDIOPLLCAL_AUDIOPLL_CALDLY_SHIFT                             1
#define     CMU_AUDIOPLLCAL_AUDIOPLL_CALDLY_MASK                              (0x3<<1)
#define     CMU_AUDIOPLLCAL_AUDIOPLL_CALEN                                    0

#define     CMU_AUDIOPLLDEBUG_AUDPLL_DBREV_E                                  15
#define     CMU_AUDIOPLLDEBUG_AUDPLL_DBREV_SHIFT                              11
#define     CMU_AUDIOPLLDEBUG_AUDPLL_DBREV_MASK                               (0x1F<<11)
#define     CMU_AUDIOPLLDEBUG_AUDIOPLL_FORCE_VC                               10
#define     CMU_AUDIOPLLDEBUG_AUDIOPLL_SET_VC_E                               9
#define     CMU_AUDIOPLLDEBUG_AUDIOPLL_SET_VC_SHIFT                           7
#define     CMU_AUDIOPLLDEBUG_AUDIOPLL_SET_VC_MASK                            (0x7<<7)
#define     CMU_AUDIOPLLDEBUG_AUDPLL_RS_MODE                                  6
#define     CMU_AUDIOPLLDEBUG_AUDIOPLL_RS_E                                   5
#define     CMU_AUDIOPLLDEBUG_AUDIOPLL_RS_SHIFT                               2
#define     CMU_AUDIOPLLDEBUG_AUDIOPLL_RS_MASK                                (0xF<<2)
#define     CMU_AUDIOPLLDEBUG_AUDIOPLL_ICP_E                                  1
#define     CMU_AUDIOPLLDEBUG_AUDIOPLL_ICP_SHIFT                              0
#define     CMU_AUDIOPLLDEBUG_AUDIOPLL_ICP_MASK                               (0x3<<0)

#define     CMU_CLKCTL0_SYS_CLK_SEL                                           15
#define     CMU_CLKCTL0_ADC_CLK_DIV_E                                         14
#define     CMU_CLKCTL0_ADC_CLK_DIV_SHIFT                                     13
#define     CMU_CLKCTL0_ADC_CLK_DIV_MASK                                      (0x3<<13)
#define     CMU_CLKCTL0_SCLK_POL_SEL                                          12
#define     CMU_CLKCTL0_SCLK_PHA_SEL                                          11
#define     CMU_CLKCTL0_SCLK_SEL                                              10
#define     CMU_CLKCTL0_SCLK_MODE_E                                           9
#define     CMU_CLKCTL0_SCLK_MODE_SHIFT                                       8
#define     CMU_CLKCTL0_SCLK_MODE_MASK                                        (0x3<<8)
#define     CMU_CLKCTL0_SCLK_DIV_E                                            7
#define     CMU_CLKCTL0_SCLK_DIV_SHIFT                                        6
#define     CMU_CLKCTL0_SCLK_DIV_MASK                                         (0x3<<6)
#define     CMU_CLKCTL0_AUDIO_CLK_SEL_E                                       5
#define     CMU_CLKCTL0_AUDIO_CLK_SEL_SHIFT                                   4
#define     CMU_CLKCTL0_AUDIO_CLK_SEL_MASK                                    (0x3<<4)
#define     CMU_CLKCTL0_AUDIO_CLK_DIV_E                                       3
#define     CMU_CLKCTL0_AUDIO_CLK_DIV_SHIFT                                   0
#define     CMU_CLKCTL0_AUDIO_CLK_DIV_MASK                                    (0xF<<0)

#define     CMU_CLKCTL1_CLK32K_DIV_E                                          15
#define     CMU_CLKCTL1_CLK32K_DIV_SHIFT                                      12
#define     CMU_CLKCTL1_CLK32K_DIV_MASK                                       (0xF<<12)
#define     CMU_CLKCTL1_DMIC67_OUT_SEL                                        11
#define     CMU_CLKCTL1_DMIC45_OUT_SEL                                        10
#define     CMU_CLKCTL1_DMIC23_OUT_SEL                                        9
#define     CMU_CLKCTL1_DMIC01_OUT_SEL                                        8
#define     CMU_CLKCTL1_DMIC_CLK_SEL                                          7
#define     CMU_CLKCTL1_CH67_DIG_SEL                                          5
#define     CMU_CLKCTL1_CH45_DIG_SEL                                          4
#define     CMU_CLKCTL1_CH23_DIG_SEL                                          3
#define     CMU_CLKCTL1_CH1_DIG_SEL                                           2
#define     CMU_CLKCTL1_CH0_DIG_SEL                                           0

#define     CMU_CLKEN0_SYSCLK_EN                                              15
#define     CMU_CLKEN0_VAD_CLK_EN                                             14
#define     CMU_CLKEN0_CH67_DIGCLK_EN                                         13
#define     CMU_CLKEN0_CH45_DIGCLK_EN                                         12
#define     CMU_CLKEN0_CH23_DIGCLK_EN                                         11
#define     CMU_CLKEN0_CH1_DIGCLK_EN                                          10
#define     CMU_CLKEN0_CH0_DIGCLK_EN1                                         9
#define     CMU_CLKEN0_CH0_DIGCLK_EN0                                         8

#define     CMU_CLKEN1_MCLK_EN                                                1
#define     CMU_CLKEN1_SCLK_EN                                                0

#define     CMU_DEVRST_AUDIO_RST                                              0

#define     CMU_ANALOGDEBUG_CMU_ADEN                                          15
#define     CMU_ANALOGDEBUG_TST_PD100K                                        10
#define     CMU_ANALOGDEBUG_TST_ANA0_DIG1                                     9
#define     CMU_ANALOGDEBUG_AUDIOPLL_TSTEN                                    8
#define     CMU_ANALOGDEBUG_AUDIOPLL_TST_SEL_E                                3
#define     CMU_ANALOGDEBUG_AUDIOPLL_TST_SEL_SHIFT                            2
#define     CMU_ANALOGDEBUG_AUDIOPLL_TST_SEL_MASK                             (0x3<<2)
#define     CMU_ANALOGDEBUG_CLKTST_SEL_E                                      1
#define     CMU_ANALOGDEBUG_CLKTST_SEL_SHIFT                                  0
#define     CMU_ANALOGDEBUG_CLKTST_SEL_MASK                                   (0x3<<0)

#define     CMU_DIGITALDEBUG_CMU_DDEN                                         15
#define     CMU_DIGITALDEBUG_CMU_DDSS_E                                       5
#define     CMU_DIGITALDEBUG_CMU_DDSS_SHIFT                                   0
#define     CMU_DIGITALDEBUG_CMU_DDSS_MASK                                    (0x3F<<0)

#define     CMU_OSC24M_CAL0_FQRCODE_E                                         7
#define     CMU_OSC24M_CAL0_FQRCODE_SHIFT                                     0
#define     CMU_OSC24M_CAL0_FQRCODE_MASK                                      (0xFF<<0)

#define     CMU_OSC24M_CAL1_RC24M_CAL_RANGESET_E                              10
#define     CMU_OSC24M_CAL1_RC24M_CAL_RANGESET_SHIFT                          9
#define     CMU_OSC24M_CAL1_RC24M_CAL_RANGESET_MASK                           (0x3<<9)
#define     CMU_OSC24M_CAL1_RC24M_CAL_INITSET_E                               8
#define     CMU_OSC24M_CAL1_RC24M_CAL_INITSET_SHIFT                           2
#define     CMU_OSC24M_CAL1_RC24M_CAL_INITSET_MASK                            (0x7F<<2)
#define     CMU_OSC24M_CAL1_RC24M_AUTOCAL_EN                                  1
#define     CMU_OSC24M_CAL1_RC24M_TUNEMODE                                    0

#define     CMU_OSC24M_CAL2_FQRMIN_E                                          8
#define     CMU_OSC24M_CAL2_FQRMIN_SHIFT                                      1
#define     CMU_OSC24M_CAL2_FQRMIN_MASK                                       (0xFF<<1)
#define     CMU_OSC24M_CAL2_INTERRUPT                                         0

#define     CMU_AVDDLDO_CTL_AVDDLDO_PD                                        3
#define     CMU_AVDDLDO_CTL_AVDDLDO_VOL_SEL_E                                 2
#define     CMU_AVDDLDO_CTL_AVDDLDO_VOL_SEL_SHIFT                             1
#define     CMU_AVDDLDO_CTL_AVDDLDO_VOL_SEL_MASK                              (0x3<<1)
#define     CMU_AVDDLDO_CTL_AVDDLDO_EN                                        0

//--------------MFP_Controller-------------------------------------------//
//--------------Register Address---------------------------------------//
#define     MFP_CONTROLLER_BASE                                               0xC0
#define     GPIO_CFG0                                                         (MFP_CONTROLLER_BASE+0x00)
#define     GPIO_CFG1                                                         (MFP_CONTROLLER_BASE+0x01)
#define     GPIO_CFG2                                                         (MFP_CONTROLLER_BASE+0x02)
#define     GPIO_DATA                                                         (MFP_CONTROLLER_BASE+0x03)
#define     GPIO_DRV0                                                         (MFP_CONTROLLER_BASE+0x04)
#define     GPIO_DRV1                                                         (MFP_CONTROLLER_BASE+0x05)
#define     GPIO_PULL0                                                        (MFP_CONTROLLER_BASE+0x06)
#define     GPIO_PULL1                                                        (MFP_CONTROLLER_BASE+0x07)
#define     GPIO_SMIT0                                                        (MFP_CONTROLLER_BASE+0x08)
#define     GPIO_SMIT1                                                        (MFP_CONTROLLER_BASE+0x09)
#define     DEBUG_SEL                                                         (MFP_CONTROLLER_BASE+0x10)
#define     DEBUG_OEN                                                         (MFP_CONTROLLER_BASE+0x11)
#define     DEBUG_IEN                                                         (MFP_CONTROLLER_BASE+0x12)
#define     BIST_CTRL                                                         (MFP_CONTROLLER_BASE+0x18)
#define     CHIP_ID                                                           (MFP_CONTROLLER_BASE+0x20)
#define     CHIP_VER                                                          (MFP_CONTROLLER_BASE+0x21)

//--------------Bits Location------------------------------------------//
#define     GPIO_CFG0_MICIN6_SEL                                              3
#define     GPIO_CFG0_MICIN4_SEL                                              2
#define     GPIO_CFG0_MICIN2_SEL                                              1
#define     GPIO_CFG0_MICIN0_SEL                                              0

#define     GPIO_CFG1_GPIO3_SEL_E                                             15
#define     GPIO_CFG1_GPIO3_SEL_SHIFT                                         12
#define     GPIO_CFG1_GPIO3_SEL_MASK                                          (0xF<<12)
#define     GPIO_CFG1_GPIO2_SEL_E                                             11
#define     GPIO_CFG1_GPIO2_SEL_SHIFT                                         8
#define     GPIO_CFG1_GPIO2_SEL_MASK                                          (0xF<<8)
#define     GPIO_CFG1_GPIO1_SEL_E                                             7
#define     GPIO_CFG1_GPIO1_SEL_SHIFT                                         4
#define     GPIO_CFG1_GPIO1_SEL_MASK                                          (0xF<<4)
#define     GPIO_CFG1_GPIO0_SEL_E                                             3
#define     GPIO_CFG1_GPIO0_SEL_SHIFT                                         0
#define     GPIO_CFG1_GPIO0_SEL_MASK                                          (0xF<<0)

#define     GPIO_CFG2_INT_SEL                                                 12
#define     GPIO_CFG2_GPIO6_SEL_E                                             11
#define     GPIO_CFG2_GPIO6_SEL_SHIFT                                         8
#define     GPIO_CFG2_GPIO6_SEL_MASK                                          (0xF<<8)
#define     GPIO_CFG2_GPIO5_SEL_E                                             7
#define     GPIO_CFG2_GPIO5_SEL_SHIFT                                         4
#define     GPIO_CFG2_GPIO5_SEL_MASK                                          (0xF<<4)
#define     GPIO_CFG2_GPIO4_SEL_E                                             3
#define     GPIO_CFG2_GPIO4_SEL_SHIFT                                         0
#define     GPIO_CFG2_GPIO4_SEL_MASK                                          (0xF<<0)

#define     GPIO_DATA_GPION_DATA_E                                            6
#define     GPIO_DATA_GPION_DATA_SHIFT                                        0
#define     GPIO_DATA_GPION_DATA_MASK                                         (0x7F<<0)

#define     GPIO_DRV0_I2C_SDA_DRV_E                                           7
#define     GPIO_DRV0_I2C_SDA_DRV_SHIFT                                       6
#define     GPIO_DRV0_I2C_SDA_DRV_MASK                                        (0x3<<6)
#define     GPIO_DRV0_I2C_SCL_DRV_E                                           5
#define     GPIO_DRV0_I2C_SCL_DRV_SHIFT                                       4
#define     GPIO_DRV0_I2C_SCL_DRV_MASK                                        (0x3<<4)
#define     GPIO_DRV0_MICINP6_DRV                                             3
#define     GPIO_DRV0_MICINP4_DRV                                             2
#define     GPIO_DRV0_MICINP2_DRV                                             1
#define     GPIO_DRV0_MICINP0_DRV                                             0

#define     GPIO_DRV1_INT_DRV_E                                               15
#define     GPIO_DRV1_INT_DRV_SHIFT                                           14
#define     GPIO_DRV1_INT_DRV_MASK                                            (0x3<<14)
#define     GPIO_DRV1_GPIO6_DRV_E                                             13
#define     GPIO_DRV1_GPIO6_DRV_SHIFT                                         12
#define     GPIO_DRV1_GPIO6_DRV_MASK                                          (0x3<<12)
#define     GPIO_DRV1_GPIO5_DRV_E                                             11
#define     GPIO_DRV1_GPIO5_DRV_SHIFT                                         10
#define     GPIO_DRV1_GPIO5_DRV_MASK                                          (0x3<<10)
#define     GPIO_DRV1_GPIO4_DRV_E                                             9
#define     GPIO_DRV1_GPIO4_DRV_SHIFT                                         8
#define     GPIO_DRV1_GPIO4_DRV_MASK                                          (0x3<<8)
#define     GPIO_DRV1_GPIO3_DRV_E                                             7
#define     GPIO_DRV1_GPIO3_DRV_SHIFT                                         6
#define     GPIO_DRV1_GPIO3_DRV_MASK                                          (0x3<<6)
#define     GPIO_DRV1_GPIO2_DRV_E                                             5
#define     GPIO_DRV1_GPIO2_DRV_SHIFT                                         4
#define     GPIO_DRV1_GPIO2_DRV_MASK                                          (0x3<<4)
#define     GPIO_DRV1_GPIO1_DRV_E                                             3
#define     GPIO_DRV1_GPIO1_DRV_SHIFT                                         2
#define     GPIO_DRV1_GPIO1_DRV_MASK                                          (0x3<<2)
#define     GPIO_DRV1_GPIO0_DRV_E                                             1
#define     GPIO_DRV1_GPIO0_DRV_SHIFT                                         0
#define     GPIO_DRV1_GPIO0_DRV_MASK                                          (0x3<<0)

#define     GPIO_PULL0_MICINP6_PULL_E                                         15
#define     GPIO_PULL0_MICINP6_PULL_SHIFT                                     14
#define     GPIO_PULL0_MICINP6_PULL_MASK                                      (0x3<<14)
#define     GPIO_PULL0_MICINN6_PULL_E                                         13
#define     GPIO_PULL0_MICINN6_PULL_SHIFT                                     12
#define     GPIO_PULL0_MICINN6_PULL_MASK                                      (0x3<<12)
#define     GPIO_PULL0_MICINP4_PULL_E                                         11
#define     GPIO_PULL0_MICINP4_PULL_SHIFT                                     10
#define     GPIO_PULL0_MICINP4_PULL_MASK                                      (0x3<<10)
#define     GPIO_PULL0_MICINN4_PULL_E                                         9
#define     GPIO_PULL0_MICINN4_PULL_SHIFT                                     8
#define     GPIO_PULL0_MICINN4_PULL_MASK                                      (0x3<<8)
#define     GPIO_PULL0_MICINP2_PULL_E                                         7
#define     GPIO_PULL0_MICINP2_PULL_SHIFT                                     6
#define     GPIO_PULL0_MICINP2_PULL_MASK                                      (0x3<<6)
#define     GPIO_PULL0_MICINN2_PULL_E                                         5
#define     GPIO_PULL0_MICINN2_PULL_SHIFT                                     4
#define     GPIO_PULL0_MICINN2_PULL_MASK                                      (0x3<<4)
#define     GPIO_PULL0_MICINP0_PULL_E                                         3
#define     GPIO_PULL0_MICINP0_PULL_SHIFT                                     2
#define     GPIO_PULL0_MICINP0_PULL_MASK                                      (0x3<<2)
#define     GPIO_PULL0_MICINN0_PULL_E                                         1
#define     GPIO_PULL0_MICINN0_PULL_SHIFT                                     0
#define     GPIO_PULL0_MICINN0_PULL_MASK                                      (0x3<<0)

#define     GPIO_PULL1_GPIO6_PULL_E                                           13
#define     GPIO_PULL1_GPIO6_PULL_SHIFT                                       12
#define     GPIO_PULL1_GPIO6_PULL_MASK                                        (0x3<<12)
#define     GPIO_PULL1_GPIO5_PULL_E                                           11
#define     GPIO_PULL1_GPIO5_PULL_SHIFT                                       10
#define     GPIO_PULL1_GPIO5_PULL_MASK                                        (0x3<<10)
#define     GPIO_PULL1_GPIO4_PULL_E                                           9
#define     GPIO_PULL1_GPIO4_PULL_SHIFT                                       8
#define     GPIO_PULL1_GPIO4_PULL_MASK                                        (0x3<<8)
#define     GPIO_PULL1_GPIO3_PULL_E                                           7
#define     GPIO_PULL1_GPIO3_PULL_SHIFT                                       6
#define     GPIO_PULL1_GPIO3_PULL_MASK                                        (0x3<<6)
#define     GPIO_PULL1_GPIO2_PULL_E                                           5
#define     GPIO_PULL1_GPIO2_PULL_SHIFT                                       4
#define     GPIO_PULL1_GPIO2_PULL_MASK                                        (0x3<<4)
#define     GPIO_PULL1_GPIO1_PULL_E                                           3
#define     GPIO_PULL1_GPIO1_PULL_SHIFT                                       2
#define     GPIO_PULL1_GPIO1_PULL_MASK                                        (0x3<<2)
#define     GPIO_PULL1_GPIO0_PULL_E                                           1
#define     GPIO_PULL1_GPIO0_PULL_SHIFT                                       0
#define     GPIO_PULL1_GPIO0_PULL_MASK                                        (0x3<<0)

#define     GPIO_SMIT0_I2C_SCL_SE                                             5
#define     GPIO_SMIT0_I2C_SDA_SE                                             4
#define     GPIO_SMIT0_MICINN6_SE                                             3
#define     GPIO_SMIT0_MICINN4_SE                                             2
#define     GPIO_SMIT0_MICINN2_SE                                             1
#define     GPIO_SMIT0_MICINN0_SE                                             0

#define     GPIO_SMIT1_CLKIN_DEB_EN                                           11
#define     GPIO_SMIT1_GPIO2_DEB_EN                                           10
#define     GPIO_SMIT1_GPIO1_DEB_EN                                           9
#define     GPIO_SMIT1_GPIO0_DEB_EN                                           8
#define     GPIO_SMIT1_GPIO6_SE                                               6
#define     GPIO_SMIT1_GPIO5_SE                                               5
#define     GPIO_SMIT1_GPIO4_SE                                               4
#define     GPIO_SMIT1_GPIO3_SE                                               3
#define     GPIO_SMIT1_GPIO2_SE                                               2
#define     GPIO_SMIT1_GPIO1_SE                                               1
#define     GPIO_SMIT1_GPIO0_SE                                               0

#define     DEBUG_SEL_DEBUG_SEL_E                                             4
#define     DEBUG_SEL_DEBUG_SEL_SHIFT                                         0
#define     DEBUG_SEL_DEBUG_SEL_MASK                                          (0x1F<<0)

#define     DEBUG_OEN_DEBUG_OE_E                                              6
#define     DEBUG_OEN_DEBUG_OE_SHIFT                                          0
#define     DEBUG_OEN_DEBUG_OE_MASK                                           (0x7F<<0)

#define     DEBUG_IEN_DEBUG_IE_E                                              6
#define     DEBUG_IEN_DEBUG_IE_SHIFT                                          0
#define     DEBUG_IEN_DEBUG_IE_MASK                                           (0x7F<<0)

#define     BIST_CTRL_BIST_FAIL                                               8
#define     BIST_CTRL_BIST_DONE                                               4
#define     BIST_CTRL_BIST_START                                              0

#define     CHIP_ID_CHIP_ID_E                                                 15
#define     CHIP_ID_CHIP_ID_SHIFT                                             0
#define     CHIP_ID_CHIP_ID_MASK                                              (0xFFFF<<0)

#define     CHIP_VER_CHIP_VER_E                                               3
#define     CHIP_VER_CHIP_VER_SHIFT                                           0
#define     CHIP_VER_CHIP_VER_MASK                                            (0xF<<0)

//---------------------------------------------------------------------//
#endif
