obj-$(CONFIG_PM_GENERIC_DOMAINS) += owl_bootmode.o
obj-$(CONFIG_PM_SLEEP) += owl_pm.o
obj-$(CONFIG_OWL_CPU_AUTO_HOTPLUG) += hotplug-owl.o
obj-y += ppm-owl/
obj-y += powergate/
obj-y += owl_dmm_pm.o
obj-y += dvfs.o
obj-y += owl_dbg.o