#
# Copyright (c) 2015 Actions Semi Co., Ltd.
#
# This software is licensed under the terms of the GNU General Public
# License version 2, as published by the Free Software Foundation, and
# may be copied, distributed, and modified under those terms.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# Author: Lipeng<lipeng@actions-semi.com>
#
# Change log:
#	2015/8/20: Created by Lipeng.

obj-$(CONFIG_VIDEO_OWL_DE) += owl_de.o

owl_de-$(CONFIG_VIDEO_OWL_DE_S900) := de-s900.o
owl_de-$(CONFIG_VIDEO_OWL_DE_S700) := de-s700.o
owl_de-$(CONFIG_VIDEO_OWL_DE_ATS3605) := de-ats3605.o
