override HOST_PRIMARY_ARCH := host_x86_64
override HOST_32BIT_ARCH := host_i386
override HOST_FORCE_32BIT := -m32
override TARGET_PRIMARY_ARCH := target_aarch64
override TARGET_SECONDARY_ARCH := target_armv7-a
override TARGET_ALL_ARCH :=  target_aarch64 target_armv7-a
override TARGET_FORCE_32BIT := 
override KERNELDIR := 
override KERNEL_ID := 3.10.52
override KERNEL_COMPONENTS := srvkm
override KERNEL_CROSS_COMPILE := 
override PVRSRV_MODNAME := pvrsrvkm
override PVR_BUILD_DIR := owl_android
override PVR_BUILD_TYPE := release
override PVR_SYSTEM := rgx_owl
override PVR_LOADER := 
override BUILD := release
override DEBUGLINK := 1
override COMPRESS_DEBUG_SECTIONS := 1
override SUPPORT_GPUTRACE_EVENTS := 1
override SUPPORT_COMPUTE := 1
override SUPPORT_TLA := 1
override OPTIM := -O2
override PVR_HANDLE_BACKEND := idr
override SUPPORT_PVRTL := 1
override SUPPORT_KERNEL_SRVINIT := 1
override SUPPORT_NATIVE_FENCE_SYNC := 1
override SUPPORT_ANDROID_PLATFORM := 1
override SUPPORT_ION := 1
