override HOST_PRIMARY_ARCH := host_x86_64
override HOST_32BIT_ARCH := host_i386
override HOST_FORCE_32BIT := -m32
override TARGET_PRIMARY_ARCH := target_aarch64
override TARGET_SECONDARY_ARCH := target_armv7-a
override TARGET_ALL_ARCH :=  target_aarch64 target_armv7-a
override TARGET_FORCE_32BIT := 
override KERNELDIR := 
override KERNEL_ID := 3.10.52
override KERNEL_COMPONENTS := srvkm
override KERNEL_CROSS_COMPILE := 
override SUPPORT_ION := 1
override PVRSRV_MODNAME := pvrsrvkm
override PVR_BUILD_DIR := owl_android
override PVR_BUILD_TYPE := release
override PVR_SYSTEM := rgx_owl
override BUILD := release
override DEBUGLINK := 1
override CACHEFLUSH_TYPE := CACHEFLUSH_GENERIC
override SUPPORT_INSECURE_EXPORT := 1
override SUPPORT_SECURE_EXPORT := 1
override SUPPORT_GPUTRACE_EVENTS := 1
override OPTIM := -O2
override PVR_HANDLE_BACKEND := generic
override SUPPORT_ANDROID_PLATFORM := 1
override PVR_ANDROID_NATIVE_WINDOW_HAS_SYNC := 1
