#
# Copyright (c) 2015 Actions Semi Co., Ltd.
#
# This software is licensed under the terms of the GNU General Public
# License version 2, as published by the Free Software Foundation, and
# may be copied, distributed, and modified under those terms.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# Author: Lipeng<lipeng@actions-semi.com>
#
# Change log:
#	2015/8/20: Created by Lipeng.

obj-$(CONFIG_VIDEO_OWL_PANELS) += owl_panel.o

owl_panel-$(CONFIG_VIDEO_OWL_GLP) += panel-glp.o
owl_panel-$(CONFIG_VIDEO_OWL_GEP) += panel-gep.o
owl_panel-$(CONFIG_VIDEO_OWL_GMP) += panel-gmp.o
owl_panel-$(CONFIG_VIDEO_OWL_GHP) += panel-ghp.o
owl_panel-$(CONFIG_VIDEO_OWL_GCP) += panel-gcp.o
owl_panel-$(CONFIG_VIDEO_OWL_GDP) += panel-gdp.o


owl_panel-$(CONFIG_VIDEO_OWL_lq055t3sx02) += panel-lq055t3sx02.o
owl_panel-$(CONFIG_VIDEO_OWL_TC358860) += panel-tc358860.o
owl_panel-$(CONFIG_VIDEO_OWL_AMOLED) += panel-amoled.o
