
obj-y                                   += headsmp.o
obj-y                                   += common.o
obj-y					+= board-owl.o
obj-y					+= cpu.o
obj-y					+= platsmp-owl.o
obj-$(CONFIG_PM_SLEEP)    += sleep-owl.o
