#
# Makefile for the Linux Wireless network device drivers.
#
obj-$(CONFIG_BCMDHD) += bcmdhd/
obj-$(CONFIG_BCMDHD_AP6335) += bcmdhd_ap6335/
obj-$(CONFIG_RTL8723BS) += rtl8723bs/
obj-$(CONFIG_RTL8188ETV) += rtl8188etv/
obj-$(CONFIG_RTL8189FS) += rtl8189fs/
obj-$(CONFIG_RTL8723BU) += rtl8723bu/
