#
# Makefile for the Linux Wireless network device drivers.
#
obj-$(CONFIG_BCMDHD) += bcmdhd/
obj-$(CONFIG_BCMDHD_AP6335) += bcmdhd_ap6335/
obj-$(CONFIG_RTL8723BS) += rtl8723bs/
#obj-$(CONFIG_rtl8188etv) += rtl8188etv/
#obj-$(CONFIG_RTL8723VQ0) += rtl8723bs-vq0/
obj-$(CONFIG_RTL8723BU) += rtl8723bu/
