#define LINUX 
#define PVR_BUILD_DIR "owl_linux"
#define PVR_BUILD_TYPE "release"
#define PVRSRV_MODNAME "pvrsrvkm"
#define SUPPORT_RGX 1
#define DISPLAY_CONTROLLER dc_drmfbdev
#define RELEASE 
#define RGX_BVNC_CORE_KM_HEADER "cores/rgxcore_km_1.75.2.30.h" 
#define RGX_BVNC_CORE_HEADER "cores/rgxcore_1.75.2.30.h"
#define RGX_BNC_CONFIG_KM_HEADER "configs/rgxconfig_km_1.V.2.30.h" 
#define RGX_BNC_CONFIG_HEADER "configs/rgxconfig_1.V.2.30.h"
#define SUPPORT_DBGDRV_EVENT_OBJECTS 
#define PDUMP_STREAMBUF_MAX_SIZE_MB 16
#define SYS_USING_INTERRUPTS 
#define CACHEFLUSH_TYPE CACHEFLUSH_GENERIC
#define SUPPORT_INSECURE_EXPORT 
#define SUPPORT_SECURE_EXPORT 
#define GPUVIRT_VALIDATION_NUM_OS 8
#define SUPPORT_LINUX_X86_WRITECOMBINE 
#define SUPPORT_LINUX_X86_PAT 
#define PVR_LINUX_USING_WORKQUEUES 
#define PVR_LINUX_MISR_USING_PRIVATE_WORKQUEUE 
#define PVR_LINUX_TIMERS_USING_WORKQUEUES 
#define PVR_LDM_DRIVER_REGISTRATION_NAME "pvrsrvkm"
#define LDM_PLATFORM 
#define PVRSRV_FULL_SYNC_TRACKING_HISTORY_LEN 256
#define SUPPORT_PERCONTEXT_FREELIST 
#define PVRSRV_ENABLE_PROCESS_STATS 
#define PVR_LINUX_PHYSMEM_MAX_POOL_PAGES 10240
#define PVR_LINUX_ARM_PAGEALLOC_FLUSH_THRESHOLD  256
#define PVR_LINUX_PHYSMEM_MIN_NUM_PAGES  256 
#define PVR_LINUX_PHYSMEM_MAX_ALLOC_ORDER  2 
#define PVR_LINUX_KMALLOC_ALLOCATION_THRESHOLD  16384 
#define SUPPORT_DRM 
#define SUPPORT_AUTH 
#define SUPPORT_DRM_DC_MODULE 
#define PVR_DRM_DRIVER_NAME "pvr"
#define DC_FBDEV_NUM_PREFERRED_BUFFERS 2
#define SUPPORT_GPU_DVFS 
