override HOST_PRIMARY_ARCH := host_arm64
override HOST_32BIT_ARCH := 
override HOST_FORCE_32BIT := 
override TARGET_PRIMARY_ARCH := target_arm64
override TARGET_SECONDARY_ARCH := 
override TARGET_ALL_ARCH :=  target_arm64 
override TARGET_FORCE_32BIT := 
override KERNELDIR := /mnt/gpu/linux-s900
override KERNEL_ID := 3.10.52-linaro-bubblegum
override KERNEL_COMPONENTS := srvkm dc_drmfbdev
override KERNEL_CROSS_COMPILE := aarch64-linux-gnu-
override PVRSRV_MODNAME := pvrsrvkm
override PVR_BUILD_DIR := owl_linux
override PVR_BUILD_TYPE := release
override DISPLAY_CONTROLLER := dc_drmfbdev
override PVR_SYSTEM := rgx_owl
override PVR_LOADER := drm_platform_module
override BUILD := release
override DEBUGLINK := 1
override CACHEFLUSH_TYPE := CACHEFLUSH_GENERIC
override SUPPORT_INSECURE_EXPORT := 1
override SUPPORT_SECURE_EXPORT := 1
override PVR_HANDLE_BACKEND := idr
override SUPPORT_DRM := 1
override SUPPORT_DRM_DC_MODULE := 1
