#
# Copyright (c) 2015 Actions Semi Co., Ltd.
#
# This software is licensed under the terms of the GNU General Public
# License version 2, as published by the Free Software Foundation, and
# may be copied, distributed, and modified under those terms.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# Author: Lipeng<lipeng@actions-semi.com>
#
# Change log:
#	2015/8/20: Created by Lipeng.

obj-$(CONFIG_VIDEO_OWL_LCDC) += lcdc.o
obj-$(CONFIG_VIDEO_OWL_EDPC) += edpc.o
obj-$(CONFIG_VIDEO_OWL_DUMMY_DISPC) += dummy_dispc.o
obj-$(CONFIG_VIDEO_OWL_HDMIC) += hdmic/
obj-$(CONFIG_VIDEO_OWL_CVBSC) += cvbsc/
obj-$(CONFIG_VIDEO_OWL_DSIC) += dsic/

