#
# Makefile for the gpio key driver
#

obj-$(CONFIG_KEYBOARD_OWL_GPIOKEY)		  += gpiokey.o
gpiokey-objs := owl_gpiokey_polled.o 






# KO_NAME = gpiokey

# PWD := $(shell pwd)

# ifeq ($(KERNELRELEASE),)
# current directory is driver
# CFGDIR = $(PWD)/../../../../../owl/platform/config

# include $(CFGDIR)/build_config.cfg
# include $(CFGDIR)/rules.make
# endif


# obj-m += $(KO_NAME).o
# $(KO_NAME)-objs    := gpio_keys_polled.o

# default:
# 	$(MAKE) -C $(KERNEL_BUILD_PATH) ARCH=$(R_ARCH) CROSS_COMPILE=$(R_CROSS_COMPILE) \
# 		EXTRA_CFLAGS="$(EXTRA_CFLAGS)" M=$(PWD) modules
	# cp $(KO_NAME).ko $(DEFAULT_MODULES_DIR)/ctp_$(KO_NAME).ko
#	cp $(KO_NAME).ko ctp_$(KO_NAME).ko

# clean:
# 	$(MAKE) -C $(KERNEL_BUILD_PATH) ARCH=$(R_ARCH) CROSS_COMPILE=$(R_CROSS_COMPILE) \
# 		M=$(PWD) clean
		
		

