#
# Makefile for the gt9xx goodix V2.4 touchscreen driver.
# editor : 66690
# date : 20170323
#

obj-$(CONFIG_TOUCHSCREEN_GT9XX_GOODIX)		  += gt9xx_goodix.o
gt9xx_goodix-objs := gt9xx.o goodix_tool.o gt9xx_update.o






# KO_NAME = gslX680

# PWD := $(shell pwd)

# ifeq ($(KERNELRELEASE),)
# # current directory is driver
# CFGDIR = $(PWD)/../../../../../owl/platform/config

# include $(CFGDIR)/build_config.cfg
# include $(CFGDIR)/rules.make
# endif


# obj-m += $(KO_NAME).o
# $(KO_NAME)-objs    := gslX680.o

# default:
	# $(MAKE) -C $(KERNEL_BUILD_PATH) ARCH=$(R_ARCH) CROSS_COMPILE=$(R_CROSS_COMPILE) \
		# EXTRA_CFLAGS="$(EXTRA_CFLAGS)" M=$(PWD) modules
	# cp $(KO_NAME).ko $(DEFAULT_MODULES_DIR)/ctp_$(KO_NAME).ko
# #	cp $(KO_NAME).ko ctp_$(KO_NAME).ko

# clean:
	# $(MAKE) -C $(KERNEL_BUILD_PATH) ARCH=$(R_ARCH) CROSS_COMPILE=$(R_CROSS_COMPILE) \
		# M=$(PWD) clean
		
		

