#
# Copyright (c) 2015 Actions Semi Co., Ltd.
#
# This software is licensed under the terms of the GNU General Public
# License version 2, as published by the Free Software Foundation, and
# may be copied, distributed, and modified under those terms.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# Author: Lipeng<lipeng@actions-semi.com>
#
# Change log:
#	2015/8/20: Created by Lipeng.
obj-$(CONFIG_VIDEO_OWL_ADF) += owl_adf.o

ccflags-y += -Idrivers/staging/android/

owl_adf-y := owl-adf-main.o common.o
